/** 
 * -------------------------------------------------
 * Copyright (c) 2014, All rights reserved. 
 * Hualala-Merchant-Management
 * 
 * @version : 0.1.0
 * @author : HuHao
 * @description : Hualala Merchant Management System.  
 * -------------------------------------------------
 */ 

(function ($, window) {
	IX.ns("Hualala");
	var TemplateList = new IX.IListManager();
	// 顶部提示框模板
	var tpl_site_toptip = [
		'<div id="site_toptip_{{id}}" class="site-toptip alert alert-{{type}} fade in">',
			'<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>',
			'<p>{{msg}}</p>',
		'</div>'
	].join('');
	TemplateList.register('tpl_site_toptip', tpl_site_toptip);

	// 模态窗口模板
	var tpl_modal_dialog = [
		'<div class="modal fade {{clz}}" id="{{id}}" data-backdrop="{{backdrop}}">',
			'<div class="modal-dialog">',
				'<div class="modal-content">',
					'<div class="modal-header">',
						'<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>',
						'<h4 class="modal-title">{{title}}</h4>',
					'</div>',
					'<div class="modal-body"></div>',
					'<div class="modal-footer">',
                        '<button class="btn btn-default btn-close" data-dismiss="modal">取消</button>',
                        '<button class="btn btn-warning btn-ok">保存</button>',
                    '</div>',
				'</div>',
			'</div>',
		'</div>'
	].join('');
	TemplateList.register('tpl_modal_dialog', tpl_modal_dialog);

	// 页面整体Layout模板
	var tpl_site_layout = [
		'<div id="ix_wrapper">',
			// Header 
            // @NOTE: 
			'<div class="navbar navbar-default navbar-fixed-top ix-header" role="navigation">',
				'<div class="header-line clearfix">',
					'<div class="container">',
						'<div class="hidden-xs pull-left">',
							'<a href="{{header.pcClientPath}}" target="_blank"><span class="icon-pcclient"></span>哗啦啦PC客户端</a>',
							'<a href="{{header.hualalaUrl}}" target="_blank"><span class="icon-jumpsite"></span>访问哗啦啦网站</a>',
						'</div>',
						'{{#if header.isLogin}}',
						'<div class="pull-right">',
							'<span class="hello">Hi</span><span class="user">{{header.loginName}},</span>',
							'<a class="logout" href="{{header.logoutPath}}">退出</a>',
						'</div>',
						'{{else}}',
						'<div class="pull-right">',
							'<span class="hello">Hi,</span><span class="">欢迎来到哗啦啦商户中心</span>',
						'</div>',
						'{{/if}}',
					'</div>',
				'</div>',
				'<div class="container">',
					'<div class="navbar-header">',
						'<a class="navbar-brand logo" href="{{header.merchantRoot}}" title="哗啦啦商户中心"><img alt="哗啦啦商户中心" src="{{header.logo}}" /></a>',
						'<h1 class="ix-group-brand">{{header.groupName}}</h1>',
					'</div>',
				'</div>',
			'</div>',
			// Body
			'<div class="ix-body">',
				'<div class="container">',
				'</div>',
			'</div>',
			// Footer
             // @NOTE: 开发阶段隐藏页脚
			'<div class="ix-footer navbar-fixed-bottom hidden">',
				'<div class="container">',
					'<p class="links">',
						'<a href="{{footer.aboutPath}}">关于哗啦啦商户中心</a>',
						'<a href="{{footer.contactPath}}">联系我们</a>',
					'</p>',
					'<p class="copyright">',
						'<img alt="Gozap" src="{{footer.gozapLogo}}"/>',
						'<span class="">&nbsp;旗下网站&nbsp;&copy;&nbsp;2014&nbsp;hualala.com&nbsp;京IPC备14019284号-3</span>',
					'</p>',
				'</div>',
			'</div>',
		'</div>'
	].join('');
	TemplateList.register('tpl_site_layout', tpl_site_layout);

	// 站点导航栏
	var tpl_site_navbar = [
		'<div class="navbar-collapse collapse" id="site_navbar">',
			'<ul class="nav nav-justified nav-pills navbar-right">',
				'{{#each items}}',
				'<li class="{{active}} {{disabled}}">',
					'<a href="{{path}}" data-page-type="{{name}}">{{label}}</a>',
				'</li>',
				// <li class="active"><a href="#">店铺管理</a></li>
				// <li class=""><a href="#about">结算</a></li>
				// <li><a href="#contact">订单</a></li>
				// <li><a href="#contact">业务设置</a></li>
				// <li><a href="#contact">帐号管理</a></li>
				'{{/each}}',
			'</ul>',
		'</div>'
	].join('');
	TemplateList.register('tpl_site_navbar', tpl_site_navbar);

	// 小屏幕下，站点导航栏的触发按钮
	var tpl_site_navbarToggle = [
		// '<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">',
		'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="{{target}}">',
			'<span class="sr-only">Toggle navigation</span>',
			'<span class="icon-bar"></span>',
			'<span class="icon-bar"></span>',
			'<span class="icon-bar"></span>',
		'</button>'
	].join('');
	TemplateList.register('tpl_site_navbarToggle', tpl_site_navbarToggle);

	// 嗅探到低版本IE浏览器后，给出高级浏览器的下载链接和相关友好提示
	var tpl_site_browserSupport = [
		'<div id="ix_wrapper">',
			'<div class="container">',
				'<div class="jumbotron support-box">',
					'<h1>让管理店铺变得更加高大上</h1>',
					'<p>{{{msg}}}</p>',
					'<p>',
						'<ul class="media-list">',
						'{{#each items}}',
							'<li class="media">',
								'<a class="pull-left" href="{{href}}">',
									'<img src="{{icon}}" alt="{{name}}" width="60" height="60" />',
								'</a>',
								'<div class="media-body">',
									'<h4 class="media-heading">',
										'<a href="{{href}}">{{name}}</a>',
									'</h4>',
									'<p>{{desc}}</p>',
								'</div>',
							'</li>',
						'{{/each}}',
						'</ul>',
					'</p>',
					'<p class="clearfix"><a class="btn btn-primary btn-lg pull-right" role="button">跳过提示，继续访问</a></p>',
				'</div>',
			'</div>',
		'</div>'
	].join('');
	TemplateList.register('tpl_site_browserSupport', tpl_site_browserSupport);

	// 登录页面
	var tpl_site_login = [
		'<div class="jumbotron login-box">',
			'<div class="row">',
				'<div class="hidden-xs col-sm-7 col-md-7 col-lg-7 login-pic">',
					'<img alt="pic" src="{{bannerImg}}" />',
				'</div>',
				'<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">',
					'<div class="panel panel-warning panel-login">',
						'<div class="panel-heading">',
							'<h3 class="panel-title">立即登录</h3>',
						'</div>',
						'<div class="panel-body">',

							'<div class="form-horizontal">',
								'<!-- Text input-->',
								'<div class="form-group">',
									'<div class="col-md-offset-1 col-md-10">',
										'<input id="group_name" name="group_name" type="text" placeholder="请输入集团主账号" class="form-control input-md" >',
									'</div>',
								'</div>',
								'<!-- Text input-->',
								'<div class="form-group">',
									'<div class="col-md-offset-1 col-md-10">',
										'<input id="group_subname" name="group_subname" type="text" placeholder="请输入集团子账号" class="form-control input-md" >',
									'</div>',
								'</div>',
								'<!-- Password input-->',
								'<div class="form-group">',
									'<div class="col-md-offset-1 col-md-10">',
										'<input id="login_pwd" name="login_pwd" type="password" placeholder="请输入登录密码" class="form-control input-md" >',
									'</div>',
								'</div>',
								'<!-- Auth code input-->',
								'<div class="form-group">',
									'<div class="col-md-offset-1 col-xs-8 col-md-7 col-lg-7">',
										'<input id="login_auth" name="login_auth" type="text" placeholder="请输入验证码" class="form-control input-md" >',
									'</div>',
									'<div class="col-xs-2 col-md-2 col-lg-2">',
										'<div class="ix-authcode">',
											'<img alt="动态验证码" class="auth-img hidden" src=""/>',
											// '<input type="hidden" name="auth_code" id="auth_code" />',
											'<div class="progress ">',
												'<div class="progress-bar progress-bar-warning progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">',
													// '<span class="sr-only">45% Complete</span>',
												'</div>',
											'</div>',
										'</div>',
									'</div>',
								'</div>',
								'<!-- Button -->',
								'<div class="form-group">',
									'<div class="col-md-offset-1 col-md-10">',
										'<button type="submit" id="login_sub" name="login_sub" class="btn btn-warning btn-lg form-control ">登录</button>',
										'<div class="progress hidden">',
											'<div class="progress-bar progress-bar-warning progress-bar-striped active"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">',
												// '<span class="sr-only">45% Complete</span>',
											'</div>',
										'</div>',
									'</div>',
								'</div>',
							'</div>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
		'</div>'
	].join('');
	TemplateList.register('tpl_site_login', tpl_site_login);

	// 首页
	var tpl_site_homepage = [
		'<div class="home-page home-brick">',
			'{{#each bricks}}',
				'<div class="{{brickClz}}">',
					'<div class="{{itemClz}} x-mul-vertical-middle"  data-pagename="{{name}}">',
						'<div class="item  x-v-m-out">',
							'<div class="x-v-m-in">',
								'<div class="format">',
									'<span class="{{icon}}"></span>',
									'<h3>{{title}}</h3>',
									'<p class="hidden-xs">{{label}}</p>',
								'</div>',
							'</div>',
						'</div>',
					'</div>',
				'</div>',
			'{{/each}}',
		'</div>'
	].join('');
	TemplateList.register('tpl_site_homepage', tpl_site_homepage);

	// 面包屑
	var tpl_site_breadcrumb = [
		'<ol class="breadcrumb x-bread-crumb {{clz}}">',
			'{{#each items}}',
				'{{#if isLastNode}}',
					'<li class="{{clz}} active">',
						'{{{label}}}',
					'</li>',
				'{{else}}',
					'<li class="{{clz}}">',
						'<a href="javascript:void(0);" data-name="{{name}}" data-href="{{path}}">{{label}}</a>',
					'</li>',
				'{{/if}}',
			'{{/each}}',
		'</ol>'
	].join('');
	TemplateList.register('tpl_site_breadcrumb', tpl_site_breadcrumb);

    // 上传图片对话框模板
    var tpl_site_uploadimg = [
        '<div class="modal fade" id="swfUploadImgDialog" tabindex="-1">',
        '<div class="modal-dialog">',
        '<div class="modal-content">',
            '<div class="modal-header">',
                '<button type="button" class="close" data-dismiss="modal">&times;</button>',
                '<h4 class="modal-title">上传图片</h4>',
            '</div>',
            '<div class="modal-body">',
                '<object type="application/x-shockwave-flash" ',
                    'id="hualalaImageUpload" name="hualalaImageUpload" ',
                    'data="" ',
                    'width="500" height="375">',
                    '<param name="quality" value="high">',
                    '<param name="allowscriptaccess" value="always">',
                    '<param name="wmode" value="transparent">',
                    '<param name="flashvars" value="">',
                '</object>',
            '</div>',
        '</div>',
        '</div>',
        '</div>'].join('');
    TemplateList.register('tpl_site_uploadimg', tpl_site_uploadimg);

    var tpl_site_modal_btns = [
		'{{#each btns}}',
			'<button type="button" class="btn {{clz}}" name="{{name}}">{{label}}</button>',
		'{{/each}}'
	].join('');
	TemplateList.register('tpl_site_modal_btns', tpl_site_modal_btns);

	// 基础数据表格模版
	var tpl_base_datagrid = [
		'<div class="table-responsive">',
			'<table class="table {{clz}}">',
				'<thead>',
					'<tr>',
						'{{#each thead}}',
							'<th class="{{clz}}">{{{label}}}</th>',
						'{{/each}}',
					'</tr>',
				'</thead>',
				'<tbody>',
					'{{#each rows}}',
						'<tr class="{{clz}}">',
							'{{#each cols}}',
								'<td class="{{clz}}">',
									'{{#chkColType type type="button"}}',
										'{{> colBtns}}',
									'{{/chkColType}}',
									'{{#chkColType type type="text"}}',
										'<p data-value="{{value}}">{{{text}}}</p>',
									'{{/chkColType}}',
								'</td>',
							'{{/each}}',
						'</tr>',
					'{{/each}}',
				'</tbody>',
			'</table>',
		'</div>'
	].join('');
	TemplateList.register('tpl_base_datagrid', tpl_base_datagrid);
	// 基础数据表格操作列
	var tpl_base_grid_colbtns = [
		'<div class="">',
			'{{#each btns}}',
				'<a href="{{link}}" class="{{clz}}" data-id="{{id}}" data-type="{{type}}">',
					'{{{label}}}',
				'</a>',
			'{{/each}}',
		'</div>'
	].join('');
	TemplateList.register('tpl_base_grid_colbtns', tpl_base_grid_colbtns);

	var TplLib = function () {
		return {
			register : function (key, tpl) {
				if (!TemplateList.hasKey(key)) {
					TemplateList.register(key, tpl);
				} else {
					throw("This key has registed!!!");
				}
			},
			get : function (key) {
				if (!TemplateList.hasKey(key)) {
					throw("There are no template that is named " + key);
				} else {
					return TemplateList.getByKeys([key])[0];
				}
			}
		};
	};

	Hualala.TplLib = new TplLib();
})(jQuery, window);;(function ($, window) {
	IX.ns("Hualala");
	var TplLib = Hualala.TplLib;
    
    var tpl_set_shop_client_pwd = [
    '<form class="form-horizontal">',
        '<div class="form-group">',
            '<label class="col-sm-3 control-label">店铺账号:</label>',
            '<div class="col-sm-9">',
                '<p class="form-control-static">{{shopID}}</p>',
            '</div>',
        '</div>',
        '<div class="form-group has-feedback">',
            '<label for="shopClinetPwd" class="col-sm-3 control-label">登录密码:</label>',
            '<div class="col-sm-9">',
                '<input type="password" id="shopClinetPwd" name="shopClinetPwd"  class="form-control" />',
                '<i class="form-control-feedback glyphicon"></i>',
                '<small class="help-block"></small>',
            '</div>',
        '</div>',
        '<div class="checkbox col-sm-offset-3">',
            '<label for="showPwd" class="control-label">',
                '<input type="checkbox" id="showPwd" name="shopClinetPwd" />',
                '显示明文',
            '</label>',
        '</div>',
    '</form>'].join('');
    TplLib.register('tpl_set_shop_client_pwd', tpl_set_shop_client_pwd);

    var tpl_shop_info_head = [
    /*'<div class="bs-callout shop-info-head">',*/
        '<div class="fl">',
            '<span class="shop-name">{{shopName}}</span>',
            '<a href="{{shopUrl}}" target="_blank">查看网上店铺</a>',
            '<a href="{{shopListLink}}">切换店铺</a>',
            '<a id="resetPwd" href="javascript:;">重置客户端密码</a>',
        '</div>',
        '<div class="shop-state">',
            '<label class="t-label">店铺当前状态：</label>',
            '<input type="checkbox" {{checked}} />',
        '</div>',
    /*'</div>'*/].join('');
    TplLib.register('tpl_shop_info_head', tpl_shop_info_head);

	var tpl_shop_create = [
	'<div id="shopCreateWizard">',
		'<ul class="step-nav">',
			'<li><a href="#tab1" data-toggle="tab"><span class="label">1</span>基本信息</a></li>',
			'<li><a href="#tab2" data-toggle="tab"><span class="label">2</span>标注地图</a></li>',
			'<li><a href="#tab3" data-toggle="tab"><span class="label">3</span>创建成功</a></li>',
		'</ul>',
		'<div class="tab-content">',
			'<!-- 第一步 -->',
			'<form class="row tab-pane feed-back-out" id="tab1">',
				'<div class="col-sm-6 col-md-4 form-horizontal">',
					'<div class="form-group">',
						'<label for="shopName" class="col-sm-3 control-label">* 店铺名称</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="shopName" name="shopName"  class="form-control" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="cityID">* 所在城市</label>',
						'<div class="col-sm-8">',
							'<select id="cityID" name="cityID" class="form-control">',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="tel">* 店铺电话</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="tel" name="tel" class="form-control" placeholder="固定电话/手机号" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="address">* 店铺地址</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="address" name="address" class="form-control" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="PCCL">* 人均消费</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="PCCL" name="PCCL" class="form-control" />',
						'</div>',
					'</div>',
				'</div>',
				'<div class="col-sm-6 col-md-4 form-horizontal">',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="operationMode">* 运营模式</label>',
						'<div class="col-sm-8">',
							'<select id="operationMode" name="operationMode" class="form-control">',
								'<option value="0">正餐</option>',
								'<option value="1">快餐</option>',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-xs-12 col-sm-3 control-label" for="openingHours">* 营业时间</label>',
						'<div class="col-xs-8">',
							'<input type="text" id="openingHoursStart" name="openingHoursStart" class="form-control d-ib mr25"  placeholder="08:30" data-default-time="08:30" />',
							'<input type="text" id="openingHoursEnd" name="openingHoursEnd" class="form-control d-ib"  placeholder="21:30" data-default-time="21:30" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="areaID">* 地标</label>',
						'<div class="col-sm-8">',
							'<select id="areaID" name="areaID" class="form-control">',
								'<option value="">--请选择--</option>',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="cuisineID1">* 菜系1</label>',
						'<div class="col-sm-8">',
							'<select id="cuisineID1" name="cuisineID1" class="form-control">',
								'<option value="">--请选择--</option>',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="cuisineID2">菜系2</label>',
						'<div class="col-sm-8">',
							'<select id="cuisineID2" name="cuisineID2" class="form-control">',
								'<option value="">--不限--</option>',
							'</select>',
						'</div>',
					'</div>',
				'</div>',
				'<div id="uploadImg" class="col-sm-6 col-md-4">',
					'<span class="t-label">请上传店铺头图，不能大于10m<br />(根据餐厅特色上传环境图或菜品图)</span>',
					'<button class="btn btn-default v-t">上传图片</button><br />',
					'<img class="m-t" src="" alt="餐厅门头图" width="200" height="200" />',
				'</div>',
			'</form>',
			'<!-- 第二步 -->',
			'<div class="tab-pane map-wrap" id="tab2">',
				'<div class="map-search row">',
					'<div class="col-sm-4">',
						'<div class="input-group search-box map-search-box">',
							'<input class="form-control map-keyword" type="text" placeholder="搜索地图" />',
							'<span class="input-group-addon glyphicon glyphicon-search map-search-btn" title="搜索"></span>',
						'</div>',
					'</div>',
					'<div class="col-sm-3 map-help">您可拖动标注获取坐标</div>',
				'</div>',
				'<div class="map_canvas" id="mapCanvas"></div>',
				'<div class="map-result"></div>',
			'</div>',
			'<!-- 第三步 -->',
			'<div class="tab-pane t-c" id="tab3">',
				'<div class="d-ib t-l">',
					'<h4>',
						'<span class="glyphicon glyphicon-ok x-ico-suc"></span>',
						'恭喜！豆捞坊（西直门店）创建成功！',
					'</h4>',
					'完成以下两个步骤，您的店铺就正式开通啦——',
					'<ul>',
						'<li>',
							'<a class="btn btn-success" href="{{pcClientPath}}" target="_blank">下载PC客户端</a>',
							'上传菜品信息',
						'</li>',
						'<li>',
							'<a id="shopSettingLink" class="btn btn-success" href="">设置店铺功能</a>',
						'</li>',
						'<li>网上餐厅正式开通啦！</li>',
					'</ul>',
				'</div>',
			'</div>',
		'</div>',
		'<div class="step-action">',
			'<button type="button" class="btn btn-default prev-step">上一步</button>',
			'<button id="nextStep" type="button" class="btn btn-warning">下一步</button>',
		'</div>',
	'</div>'].join('');
	TplLib.register('tpl_shop_create', tpl_shop_create);
    
    var tpl_shop_info = [
    '<form class="row shop-info feed-back-out read-mode">',
        '<div class="col-sm-6 col-lg-3 form-horizontal">',
            '<div class="form-group">',
                '<label for="shopName" class="col-sm-3 control-label">店铺名称</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{shopName}}</p>',
                    '<input type="text" id="shopName" name="shopName"  class="form-control" value="{{shopName}}" />',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="cityID">所在城市</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{cityName}}</p>',
                    '<select id="cityID" name="cityID" class="form-control">',
                        '<option value="">--请选择--</option>',
                    '</select>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="tel">店铺电话</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{tel}}</p>',
                    '<input type="text" id="tel" name="tel" class="form-control" placeholder="固定电话/手机号" value="{{tel}}" />',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="address">店铺地址</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{address}}</p>',
                    '<input type="text" id="address" name="address" class="form-control" value="{{address}}" />',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="PCCL">人均消费</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{PCCL}}</p>',
                    '<input type="text" id="PCCL" name="PCCL" class="form-control" value="{{PCCL}}" />',
                '</div>',
            '</div>',
        '</div>',
        '<div class="col-sm-6 col-lg-3 form-horizontal">',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="operationMode">运营模式</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{operationModeName}}</p>',
                    '<select id="operationMode" name="operationMode" class="form-control">',
                        '<option value="0">正餐</option>',
                        '<option value="1">快餐</option>',
                    '</select>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-xs-12 col-sm-3 control-label" for="openingHours">营业时间</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{openingHours}}</p>',
                    '<input type="text" id="openingHoursStart" name="openingHoursStart" class="form-control d-ib mr25"  placeholder="08:30" data-default-time="08:30" value="{{openingHoursStart}}" />',
                    '<input type="text" id="openingHoursEnd" name="openingHoursEnd" class="form-control d-ib"  placeholder="21:30" data-default-time="21:30"  value="{{openingHoursEnd}}" />',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="areaID">地标</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{areaName}}</p>',
                    '<select id="areaID" name="areaID" class="form-control">',
                        '<option value="">--请选择--</option>',
                    '</select>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label" for="cuisineID1">菜系1</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{cuisineName1}}</p>',
                    '<select id="cuisineID1" name="cuisineID1" class="form-control">',
                        '<option value="">--请选择--</option>',
                    '</select>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label no-require" for="cuisineID2">菜系2</label>',
                '<div class="col-sm-9">',
                    '<p class="form-control-static">{{cuisineName2}}</p>',
                    '<select id="cuisineID2" name="cuisineID2" class="form-control">',
                        '<option value="">--不限--</option>',
                        '<option value="1">北京小吃</option>',
                    '</select>',
                '</div>',
            '</div>',
        '</div>',
        '<div id="uploadImg" class="col-sm-6 col-lg-3 t-r">',
            '<img class="mb-12" src="/src/img/shop_head_img_default.png" alt="餐厅门头图" width="200" height="200" /><br />',
            '<a href="javascript:;">修改门头图</a>',
        '</div>',
        '<div class="col-sm-6 col-lg-3">',
            '<div class="input-group search-box">',
                '<input class="form-control map-keyword" type="text" placeholder="搜索地图" />',
                '<span class="input-group-addon glyphicon glyphicon-search map-search-btn" title="搜索"></span>',
            '</div>',
            '<div class="map_canvas" id="mapCanvas"></div>',
            '<div class="map-result mb-12"></div>',
            '<p class="t-r mb50"><a id="remarkMap" href="javascript:;">重新标记</a></p>',
        '</div>',
        '<div class="step-action">',
            '<button id="editBtn" class="btn btn-warning">修改</button>',
            '<button id="saveBtn" class="btn btn-warning">保存</button>',
        '</div>',
    '</form>'].join('');
    TplLib.register('tpl_shop_info', tpl_shop_info);
    
    var tpl_shop_menu = [
    '<div class="shop-menu">',
        '<div id="foodClassBox" class="panel panel-default food-class"></div>',
        '<form id="foodSearch" class="panel panel-default form-inline food-search">',
            '<div class="form-group">',
                '<select id="takeawayTag" class="form-control">',
                    '<option value="">全部菜品</option>',
                    '<option value="0">堂食菜品</option>',
                    '<option value="1">外卖菜品</option>',
                '</select>',
                '<label><input type="checkbox" id="isSpecialty" value=""/> 招牌</label>',
                '<label><input type="checkbox" id="isRecommend" /> 推荐</label>',
                '<label><input type="checkbox" id="isNew" /> 新品</label>',
                '<label><input type="checkbox" id="isSetFood" /> 套餐</label>',
                '<label><input type="checkbox" id="isDiscount" /> 打折</label>',
                '<label><input type="checkbox" id="foodIsActive" /> 启用菜品</label>',
                '<label><input type="checkbox" id="isHasImage" /> 无图</label>',
                '<span class="input-group search-box">',
                    '<input type="text" id="foodName" placeholder="输入菜品名称" class="form-control" />',
                    '<span id="btnSearchFood" class="input-group-addon glyphicon glyphicon-search" title="搜索"></span>',
                '</span>',
            '</div>',
        '</form>',
        '<div id="foodSearchInfo">相关结果 (<span></span>)</div>',
        '<table class="tbl-foods">',
            '<thead>',
                '<tr>',
                    '<th width="92px">上传图片</th>',
                    '<th width="120px">名称</th>',
                    '<th>规格及单价 (<em>会员价</em><b>售价</b><span>原价</span>)</th>',
                    '<th width="">打折</th>',
                    '<th width="">是否外送</th>',
                    '<th width="">打包费(元)</th>',
                    '<th width="">是否在售</th>',
                    '<th width="200px"></th>',
                '</tr>',
            '</thead>',
            '<tbody></tbody>',
        '</table>',
    '</div>'].join('');
    TplLib.register('tpl_shop_menu', tpl_shop_menu);
    
    var tpl_food = [
    '{{#each foods}}',
        '<tr data-id="{{foodID}}" data-cid="{{foodCategoryID}}">',
            '<td><img src="{{imgSrc}}" /></td>',
            '<td>{{foodName}}</td>',
            '<td>',
            '{{#each units}}',
                '<p><span>{{unit}}</span><em>{{vipPrice}}</em><b>{{prePrice}}</b><i>{{price}}</i></p>',
            '{{/each}}',
            '</td>',
            '<td class="{{discountIco}}"></td>',
            '<td class="{{takeawayIco}}"></td>',
            '<td><b>{{takeoutPackagingFee}}</b></td>',
            '<td class="{{activeIco}}"></td>',
            '<td><span class="label label-default">修改</span></td>',
        '</tr>',
    '{{/each}}'].join('');
    TplLib.register('tpl_food', tpl_food);

	var tpl_shop_filter = [
		'<div class="{{type}}">',
			'<span class="label">{{name}}</span>',
			'{{#each items}}',
				'<a class="btn btn-link {{focusClz}}" href="javascript:void(0);" data-{{type}}="{{code}}">',
					'{{name}}',
					'{{#if count}}',
						'<i class="num">({{count}})</i>',
					'{{/if}}',
				'</a>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_filter', tpl_shop_filter);

	var tpl_shop_query = [
		'<div class="shop-query {{clz}}">',
			'<div class="filter">',
				'{{#with shopCity}}',
				'{{> shopCity}}',
				'{{/with}}',
				// '{{> shopArea}}',
			'</div>',
			'<nav class="navbar navbar-default query" role="query">',
				'<div class="container-fluid">',
					'<div class="navbar-header">',
						'{{#with toggle}}',
						'{{> toggle}}',
						'{{/with}}',
						'<a class="navbar-brand" href="javascript:void(0);">查询店铺</a>',
					'</div>',
					'<div class="collapse navbar-collapse" id="shop_query">',
						'<div class="navbar-form navbar-left" role="search">',
							'<select class="hidden">',
								'{{#each optGrp}}',
									'<optgroup label="{{name}}">',
										'{{#each items}}',
											'<option value="{{code}}">{{name}}</option>',
										'{{/each}}',
									'</optgroup>',
								'{{/each}}',
							'</select>',
							'<div class="input-group">',
								'<input type="text" class="form-control" autocomplete="off" />',
								'<span class="input-group-btn">',
									'<button class="btn btn-default">查询</button>',
								'</span>',
							'</div>',
						'</div>',
						'{{#if needShopCreate}}',
							'<button class="btn btn-warning create-shop pull-right" style="margin-top:8px;">创建店铺</button>',
						'{{/if}}',
					'</div>',
				'</div>',
			'<nav>',
		'</div>',

		/*<div class="shop-query">',
			'<div class="filter">',
				'<div class="city">',
					'<span class="label">城市：</span>',
					'<a class="btn btn-link disabled">全部</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
				'</div>',
				'<div class="area">',
					'<span class="label">区域：</span>',
					'<a class="btn btn-link disabled">全部</a>',
					'<a class="btn btn-link">海淀</a>',
					'<a class="btn btn-link">朝阳</a>',
					'<a class="btn btn-link">大兴</a>',
					'<a class="btn btn-link">回龙观</a>',
					'<a class="btn btn-link">昌平</a>',
					'<a class="btn btn-link">龙泽</a>',
					'<a class="btn btn-link">顺义</a>',
				'</div>',
			'</div>',
			'<nav class="navbar navbar-default query" role="navigation">',
				'<div class="container-fluid">',
					'<div class="navbar-header">',
						'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#shop_query">',
							'<span class="sr-only">Toggle navigation</span>',
							'<span class="icon-bar"></span>',
							'<span class="icon-bar"></span>',
							'<span class="icon-bar"></span>',
						'</button>',
						'<a class="navbar-brand" href="javascript:void(0);">查询店铺</a>',
					'</div>',
					'<div class="collapse navbar-collapse" id="shop_query">',
						'<div class="navbar-form navbar-left" role="search">',
							'<div class="input-group">',
								'<input type="text" class="form-control" autocomplete="off" />',
								'<span class="input-group-btn">',
									'<button class="btn btn-default">查询</button>',
								'</span>',
							'</div>',
						'</div>',
						'<button class="btn btn-warning create-shop pull-right" style="margin-top:8px;">创建店铺</button>',
					'</div>',
				'</div>',
			'</nav>',
		'</div>*/
	].join('');
	TplLib.register('tpl_shop_query', tpl_shop_query);

	var tpl_shop_tags = [
		'<div class="tags">',
			'{{#each tags}}',
				'<span class="label {{clz}}" title="{{tag}}">{{tag}}</span>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_tags', tpl_shop_tags);

	var tpl_shop_list_item = [
		'<div class="shop-list-item col-xs-12 {{clz}} ">',
			'<div class="row shop-base-info">',
				'<div class="col-xs-6 col-sm-3 col-md-2">',
					'<h4>{{shopName}}</h4>',
				'</div>',
				'<div class="hidden-xs col-sm-4 col-md-7 ">',
					'<div class="account {{hideAccount}}">',
						'<label class="account-label">结算账户：</label>',
						'<span class="account-name">{{settleName}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6 col-sm-5 col-md-3">',
					'<div class="switcher-wrapper pull-right">',
						'<label class="">店铺当前状态：</label>',
						'<input type="checkbox" name="{{switcherName}}" data-shop="{{shopID}}" {{shopOpen}} />',
					'</div>',
				'</div>',
			'</div>',
			'{{#each business}}',
			'<div class="row shop-business">',
				'<div class="col-xs-6 col-sm-3 col-md-2">',
					'<h4>',
						'<span class="{{icon}}"></span>',
						'{{label}}',
					'</h4>',
				'</div>',
				'<div class="col-xs-6 col-sm-2 col-md-2">',
					'<div class="switcher-wrapper">',
						'<input type="checkbox" name="{{switcherName}}" data-shop="{{shopID}}" data-business="{{type}}" data-business-id="{{id}}" {{open}} />',
					'</div>',
				'</div>',
				'<div class="col-xs-12 col-sm-6 col-md-7">',
					'<p>{{desc}}</p>',
				'</div>',
				'<div class="col-xs-12 col-sm-1 col-md-1">',
					'<button type="button" class="btn btn-default pull-right" name="business_edit" data-shop="{{shopID}}" data-business="{{type}}"  data-business-id="{{id}}">修改</button>',
				'</div>',
			'</div>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_list_item', tpl_shop_list_item);

	var tpl_shop_card = [
		'<div class="panel panel-default ix-card shop-card {{clz}}" >',
			'<div class="panel-heading ix-card-header">',
				'<h4 class="panel-title">{{name}}</h4>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="media">',
					'<a class="pull-left" href="javascript:void(0);">',
						'<img class="media-object" alt="{{name}}" src="{{img}}" />',
					'</a>',
					'<div class="media-body">',
						'{{> shopTag}}',
						'<address title="{{address}}">{{slugAddr}}</address>',
						'<div class="phone">{{tel}}</div>',
					'</div>',
					'<div class="btns pull-right">',
						'<a href="javascript:void(0);" class="btn btn-default shop-info" data-href="{{infoHref}}">',
							'修改店铺信息',
						'</a>',
						'<a href="javascript:void(0);" class="btn btn-default shop-menu" data-href="{{menuHref}}">',
							'菜谱管理',
						'</a>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<label>店铺当前状态：</label>',
				'<input type="checkbox" name="switcher" data-shop="{{id}}" class="shop-switch" {{checked}} />',
                '</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_card', tpl_shop_card);

	var tpl_shop_list = [
		'{{#with shopCard}}',
			'{{#each list}}',
			'<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">',
				'{{> shopCard}}',
			'</div>',
			'{{/each}}',
		'{{/with}}',
		'{{#with shopItem}}',
			'{{#each list}}',
				'{{> shopItem}}',
			'{{/each}}',
		'{{/with}}',
		'{{#with shopTable}}',
			'{{> shopTable}}',
		'{{/with}}'
	].join('');
	TplLib.register('tpl_shop_list', tpl_shop_list);

	var tpl_shop_table = [
		'<div class="col-xs-12 table-responsive">',
			'<table class="table">',
				'<thead>',
					'<tr>',
						'<th>城市</th>',
						'<th>店铺ID</th>',
						'<th>店铺名称</th>',
					'</tr>',
				'</thead>',
				'<tbody>',
					'{{#each rows}}',
						'<tr class="{{clz}}">',
							'<td class="">',
								'{{city}}',
							'</td>',
							'<td class="">',
								'{{id}}',
							'</td>',
							'<td class="">',
								'{{name}}',
							'</td>',
						'</tr>',
					'{{/each}}',
				'</tbody>',
			'</table>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_table', tpl_shop_table);

	var tpl_shop_list_layout = [
		'<div class="shop-list">',
			'<div class="row shop-list-body">',
			'</div>',
			'<div class="shop-list-footer clearfix">',
				'<div class="page-selection pull-right"></div>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_list_layout', tpl_shop_list_layout);

	var tpl_shop_service_form_layout = [
		'<form class="form-horizontal {{formClz}}" role="form">',
			'{{#each items}}',
				'{{#checkFormElementType type type="combo"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<select id="{{id}}" name="{{name}}" class="form-control"  data-type="{{type}}">',
								'{{#each options}}',
									'<option value="{{value}}" {{selected}}>{{label}}</option>',
								'{{/each}}',
							'</select>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="text"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#isInputGroup prefix surfix}}',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'{{else}}',
								'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
							'{{/isInputGroup}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="switcher"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'<input type="checkbox" id="{{id}}" name="{{name}}" value="{{defaultVal}}" data-type="{{type}}" data-onLabel="{{onLabel}}" data-offLabel="{{offLabel}}" {{checked}} />',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="section"}}',
					'<div class="form-group section">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'{{#with min}}',
							'<div class="min-input {{clz}}">',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'</div>',
						'{{/with}}',
						'{{#with max}}',
							// '<div class="col-sm-1 hidden-xs hidden-sm"><span class="to-label">到</span></div>',
							'<div class="max-input {{clz}}">',
								'<span class="to-label hidden-xs hidden-sm">到</span>',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'</div>',
						'{{/with}}',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="hidden"}}',
					'<input type="hidden" id="{{id}}" name="{{name}}" value="{{value}}" />',
				'{{/checkFormElementType}}',
			'{{/each}}',
		'</form>'
	].join('');
	TplLib.register('tpl_shop_service_form_layout', tpl_shop_service_form_layout);

	var tpl_shop_modal_btns = [
		'{{#each btns}}',
			'<button type="button" class="btn {{clz}}" name="{{name}}">{{label}}</button>',
		'{{/each}}'
	].join('');
	TplLib.register('tpl_shop_modal_btns', tpl_shop_modal_btns);
})(jQuery, window);;(function ($, window) {
	IX.ns("Hualala");
	var TplLib = Hualala.TplLib;
	var tpl_account_list_layout = [
		'<div class="account-list">',
			'<div class="row account-list-body">',
			'</div>',
			'<div class="account-list-footer">',
				'<div class="page-selection pull-right"></div>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_list_layout', tpl_account_list_layout);

	var tpl_account_card = [
		'<div class="panel panel-default ix-card bank-card {{clz}}" data-id="{{settleUnitID}}">',
			'<div class="panel-heading ix-card-header">',
				'<h4 class="panel-title">',
					'{{#if hasDefault}}',
					'<span class="label label-default">默认</span>',
					'{{/if}}',
					'<span class="account-name" title="{{settleUnitName}}">{{settleUnitName}}</span>',
				'</h4>',
				'<a href="javascript:void(0);" class="btn btn-success withdraw">提现</a>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="cash">',
					'<strong>{{settleBalance}}</strong>',
					'<span>元</span>',
				'</div>',
				'<div class="bank">',
					'<span class="{{bankIcon}}"></span>',
					'<span class="name">{{bankComName}}</span>',
					'<span class="num">{{{bankAccountStr}}}</span>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<span class="shops pull-left">',
					'{{shopCount}}家店',
				'</span>',
				'{{# if isDetail }}',
					'<div class="btn-group pull-right visible-xs-inline-block">',
						'{{#each acts}}',
							'{{#if isFirst}}',
								'<button type="button" class="btn btn-info" data-act="{{act}}">{{label}}</button>',
								'<button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">',
									'<span class="caret"></span>',
									'<span class="sr-only">Toggle Dropdown</span>',
								'</button>',
								'<ul class="dropdown-menu" role="menu">',
							'{{else}}',
								'<li><a href="javascript:void(0);" data-act="{{act}}">{{label}}</a></li>',
							'{{/if}}',
						'{{/each}}',
						'</ul>',
						
					'</div>',
				'{{else}}',
					'<a class="btn btn-link pull-right" data-href="{{path}}">详情&gt;</a>',
				'{{/if}}',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_card', tpl_account_card);

	var tpl_account_list = [
		'{{#with accountCard}}',
			'{{#each list}}',
			'<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">',
				'{{> accountCard}}',
			'</div>',
			'{{/each}}',
			'<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">',
				'{{> addAccountCard}}',
			'</div>',
		'{{/with}}',
	].join('');
	TplLib.register('tpl_account_list', tpl_account_list);

	var tpl_withdraw_form = [
		'<div class="table-responsive">',
			'<table class="table table-striped table-bordered">',
				'<tbody>',
				'{{#each accountInfo}}',
					'<tr>',
						'<th>{{label}}</th>',
						'<td>{{{value}}}</td>',
					'</tr>',
				'{{/each}}',
				'</tbody>',
			'</table>',
		'</div>',
		'<form class="form-horizontal {{formClz}}" role="form">',
			'<div class="form-group">',
				'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
				'<div class="{{clz}}">',
					'<div class="input-group">',
						'<span class="input-group-addon">￥</span>',
						'<input type="text" id="{{id}}" name="{{name}}" class="form-control" value="{{value}}" />',
						'<span class="input-group-addon">元</span>',
					'</div>',
				'</div>',
			'</div>',
		'</form>'
	].join('');
	TplLib.register('tpl_withdraw_form', tpl_withdraw_form);

	var tpl_addAccount_Card = [
		'<div class="panel panel-default ix-card bank-card create-account">',
			'<div class="panel-heading ix-card-header hidden">',
				'<h4 class="panel-title"></h4>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="x-mul-vertical-middle">',
					'<div class="item  x-v-m-out">',
						'<div class="x-v-m-in">',
							'<div class="ix-cross">',
								'<div class="x-cross-inner"></div>',
							'</div>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<a class="btn btn-link pull-right" href="javascript:void(0);" data-href="{{path}}">添加账户</a>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_addAccount_Card', tpl_addAccount_Card);

	var tpl_accountMgr_layout = [
		'<nav class="account-nav">',
		'</nav>',
		'<section class="account-schema-box">',
		'</section>',
		'<section class="account-detail-box">',
		'</section>'
	].join('');
	TplLib.register('tpl_accountMgr_layout', tpl_accountMgr_layout);

	var tpl_account_schema = [
		'<div class="account-schema clearfix">',
			'{{#with accountCard}}',
				'{{> accountCard}}',
			'{{/with}}',
			'<div class="account-btns hidden-xs">',
				'<ul class="nav nav-pills pull-right" role="tablist">',
					'{{#each acts}}',
						'<li role="presentation"><a href="javascript:void(0);" class="btn {{clz}}" data-act="{{act}}">{{label}}</a></li>',
					'{{/each}}',
				'</ul>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_schema', tpl_account_schema);

	var tpl_account_detail = [
		'<div class="account-detail">',
			'<h4>查看交易明细</h4>',
			'<div class="well well-sm query-form">',
				'{{#with query}}',
					'{{> transaQueryForm}}',
				'{{/with}}',
			'</div>',
			'<div class="query-result">',
				'{{#with result}}',
					'{{> transaQueryResult}}',
				'{{/with}}',
			'</div>',
			'<div class="page-selection pull-right"></div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_detail', tpl_account_detail);


	var tpl_transaQuery_form = [
		'<form class="form-horizontal" role="">',
			'<div class="row">',
				'{{#each cols}}',
					'<div class="{{colClz}}">',
						'{{#each items}}',
							'{{#checkFormElementType type type="combo"}}',
								'<div class="form-group">',
									'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
									'<div class="{{clz}}">',
										'<select id="{{id}}" name="{{name}}" class="form-control"  data-type="{{type}}">',
											'{{#each options}}',
												'<option value="{{value}}" {{selected}}>{{label}}</option>',
											'{{/each}}',
										'</select>',
									'</div>',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="section"}}',
								'<div class="form-group section">',
									'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
									'{{#with min}}',
										'<div class="min-input {{clz}}">',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'</div>',
									'{{/with}}',
									'{{#with max}}',
										// '<div class="col-sm-1 hidden-xs hidden-sm"><span class="to-label">到</span></div>',
										'<div class="max-input {{clz}}">',
											'<span class="to-label">到</span>',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'</div>',
									'{{/with}}',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="button"}}',
								'<button type="button" class="btn {{clz}}">{{{label}}}</button>',
							'{{/checkFormElementType}}',
						'{{/each}}',
					'</div>',
				'{{/each}}',
			'</div>',
		'</form>'
	].join('');
	TplLib.register('tpl_transaQuery_form', tpl_transaQuery_form);

	var tpl_transaQuery_result = [
		'<div class="table-responsive">',
			'<table class="table {{clz}}">',
				'<thead>',
					'<tr>',
						'{{#each thead}}',
							'<th class="{{clz}}">{{label}}</th>',
						'{{/each}}',
					'</tr>',
				'</thead>',
				'<tbody>',
					'{{#each rows}}',
						'<tr class="{{clz}}">',
							'{{#each cols}}',
								'<td class="{{clz}}">',
									'{{#chkColType type type="button"}}',
										'<a href="javascript:void(0);" class="{{btnClz}}" data-id="{{SUATransItemID}}" data-type="{{transType}}" data-orderid="{{orderID}}" data-orderkey="{{orderKey}}" >{{label}}</a>',
									'{{/chkColType}}',
									'{{#chkColType type type="text"}}',
										'<p data-value="{{value}}">{{{text}}}</p>',
									'{{/chkColType}}',
								'</td>',
							'{{/each}}',
						'</tr>',
					'{{/each}}',
				'</tbody>',
			'</table>',
		'</div>'
	].join('');
	TplLib.register('tpl_transaQuery_result', tpl_transaQuery_result);

	var tpl_account_edit = [
		'<form class="form-horizontal {{formClz}}" role="form">',
			'{{#each items}}',
				'{{#checkFormElementType type type="combo"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<select id="{{id}}" name="{{name}}" class="form-control"  data-type="{{type}}">',
								'{{#each options}}',
									'<option value="{{value}}" {{selected}}>{{label}}</option>',
								'{{/each}}',
							'</select>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="text"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#isInputGroup prefix surfix}}',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'{{else}}',
								'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
							'{{/isInputGroup}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="switcher"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'<input type="checkbox" id="{{id}}" name="{{name}}" value="{{defaultVal}}" data-type="{{type}}" data-onLabel="{{onLabel}}" data-offLabel="{{offLabel}}" {{checked}} />',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="radiogrp"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#each options}}',
								'<label class="{{clz}}">',
									'<input type="radio" name="{{name}}" id="{{id}}" value="{{value}}" {{checked}} />',
									'{{label}}',
								'</label>',
							'{{/each}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
			'{{/each}}',
		'</form>'
	].join('');
	TplLib.register('tpl_account_edit', tpl_account_edit);

	var tpl_account_query_shop = [
		'<div class="query-shop {{clz}}">',
			'<p class="title">',
				'{{label}}:<strong>{{title}}</strong>',
			'</p>',
			'<div class="query-box"></div>',
			'<div class="result-box"></div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_query_shop', tpl_account_query_shop);

	var tpl_orderpay_detail = [
		'<div class="row order-detail">',
			'<div class="col-xs-7 col-sm-7 col-md-8 col-lg-9">',
				'{{#each fieldsets}}',
					'{{log label}}',
					'{{#chkFieldType fieldType type="list"}}',
						'<h5>{{label}}{{{orderSubTypeLabel}}}</h5>',
						'<div class="row">',
							'{{#each fields}}',
								'{{log @key}}',
								'<div class="detail-item {{clz}}">',
									'<label>{{label}}:</label>',
									'<span>',
										'{{{value}}}',
									'</span>',
								'</div>',

							'{{/each}}',
						'</div>',
					'{{/chkFieldType}}',
					'{{#chkFieldType fieldType type="table"}}',
						'<h5>{{label}}</h5>',
						'<div class="table-responsive">',
							'<table class="table table-condensed table-hover table-striped">',
								'<thead>',
									'<tr>',
										'<th>名称</th>',
										'<th>类型</th>',
										'<th>价格</th>',
										'<th>份数</th>',
									'</tr>',
								'</thead>',
								'<tbody>',
									'{{#each categories}}',
										'<tr>',
											'<th colspan="4">',
												'{{foodCategoryName}}',
												'{{foodCategorySum}}',
											'</th>',
										'</tr>',
										'{{#each rows}}',
											'<tr>',
												'<td>{{foodName}}</td>',
												'<td>{{foodUnit}}</td>',
												'<td>{{foodPrice}}</td>',
												'<td>{{foodAmount}}</td>',
											'</tr>',
										'{{/each}}',
									'{{/each}}',
								'</tbody>',
							'</table>',
						'</div>',
					'{{/chkFieldType}}',
				'{{/each}}',
			'</div>',
			'<div class="col-xs-5 col-sm-5 col-md-4 col-lg-3">',
				'{{#with printDetail}}',
					'<h5>{{label}}{{{orderSubTypeLabel}}}</h5>',
					'<p>',
						'{{{content}}}',
					'</p>',
				'{{/with}}',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_orderpay_detail', tpl_orderpay_detail);

	var tpl_fsmcustomer_detail = [
		'{{#with settleUnitDetail}}',
			'<h5>结算账户信息</h5>',
			'<div class="{{clz}} row settle-detail">',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">账户名称：</label>',
						'<span class="col-xs-12 col-sm-7">{{settleUnitName}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">结算时间：</label>',
						'<span class="col-xs-12 col-sm-7">{{transSuccessTime}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">交易类型：</label>',
						'<span class="col-xs-12 col-sm-7">{{transTypeLabel}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">交易金额：</label>',
						'<span class="col-xs-12 col-sm-7">{{transAmount}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">扣除佣金：</label>',
						'<span class="col-xs-12 col-sm-7">{{transSalesCommission}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">结算金额：</label>',
						'<span class="col-xs-12 col-sm-7">{{transAfterBalance}}元</span>',
					'</div>',
				'</div>',
			'</div>',
		'{{/with}}',
		'{{#with customerCard}}',
			'<h5>交易明细</h5>',
			'<div class="{{clz}} row customer-detail">',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">充值金额：</label>',
						'<span class="col-xs-12 col-sm-7">{{saveMoneyTotal}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员账户余额：</label>',
						'<span class="col-xs-12 col-sm-7">{{moneyBalance}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员卡号：</label>',
						'<span  class="col-xs-12 col-sm-7">{{cardNO}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员手机号：</label>',
						'<span  class="col-xs-12 col-sm-7">{{customerMobile}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员姓名：</label>',
						'<span  class="col-xs-12 col-sm-7">{{customerName}}</span>',
					'</div>',
				'</div>',
			'</div>',
		'{{/with}}',
	].join('');
	TplLib.register('tpl_fsmcustomer_detail', tpl_fsmcustomer_detail);

})(jQuery, window);;(function ($, window) {
	IX.ns("Hualala");
	var TplLib = Hualala.TplLib;
	var tpl_order_subnav = [
		'<div class="navbar-collapse collapse" id="order_navbar">',
			'<ul class="nav nav-justified nav-pills">',
				'{{#each items}}',
				'<li class="{{active}} {{disabled}}">',
					'<a href="{{path}}" data-page-type="{{name}}">{{label}}</a>',
				'</li>',
				'{{/each}}',
			'</ul>',
		'</div>'
	].join('');
	TplLib.register('tpl_order_subnav', tpl_order_subnav);

	var tpl_order_queryLayout = [
		'<div class="well well-sm query-form">',
			'{{#with query}}',
				'{{> orderQueryForm}}',
			'{{/with}}',
		'</div>'
	].join('');
	TplLib.register('tpl_order_queryLayout', tpl_order_queryLayout);

	var tpl_order_queryForm = [
		'<form class="form-horizontal" role="">',
			'<div class="row">',
				'{{#each cols}}',
					'<div class="{{colClz}}">',
						'{{#each items}}',
							'{{#checkFormElementType type type="combo"}}',
								'<div class="form-group">',
									'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
									'<div class="{{clz}}">',
										'<select id="{{id}}" name="{{name}}" class="form-control"  data-type="{{type}}">',
											'{{#each options}}',
												'<option value="{{value}}" {{selected}}>{{label}}</option>',
											'{{/each}}',
										'</select>',
									'</div>',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="section"}}',
								'<div class="form-group section">',
									'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
									'{{#with min}}',
										'<div class="min-input {{clz}}">',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'</div>',
									'{{/with}}',
									'{{#with max}}',
										// '<div class="col-sm-1 hidden-xs hidden-sm"><span class="to-label">到</span></div>',
										'<div class="max-input {{clz}}">',
											// '<span class="to-label">到</span>',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'</div>',
									'{{/with}}',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="text"}}',
								'<div class="form-group">',
									'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
									'<div class="{{clz}}">',
										'{{#isInputGroup prefix surfix}}',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'{{else}}',
											'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
										'{{/isInputGroup}}',
									'</div>',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="button"}}',
								'<button type="button" class="btn {{clz}}">{{{label}}}</button>',
							'{{/checkFormElementType}}',
						'{{/each}}',
					'</div>',
				'{{/each}}',
			'</div>',
		'</form>'
	].join('');
	TplLib.register('tpl_order_queryForm', tpl_order_queryForm);

	var tpl_order_comboOpts = [
		'{{#each opts}}',
			'<option value="{{value}}" {{selected}}>{{label}}</option>',
		'{{/each}}'
	].join('');
	TplLib.register('tpl_order_comboOpts', tpl_order_comboOpts);

})(jQuery, window);