(function ($, window) {
	IX.ns("Hualala");
	var TplLib = Hualala.TplLib;
	var tpl_account_list_layout = [
		'<div class="account-list">',
			'<div class="row account-list-body">',
			'</div>',
			'<div class="account-list-footer">',
				'<div class="page-selection pull-right"></div>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_list_layout', tpl_account_list_layout);

	var tpl_account_card = [
		'<div class="panel panel-default ix-card bank-card {{clz}}" data-id="{{settleUnitID}}">',
			'<div class="panel-heading ix-card-header">',
				'<h4 class="panel-title">',
					'{{#if hasDefault}}',
					'<span class="label label-default">默认</span>',
					'{{/if}}',
					'<span class="account-name" title="{{settleUnitName}}">{{settleUnitName}}</span>',
				'</h4>',
				'<a href="javascript:void(0);" class="btn btn-success withdraw {{disableWithdraw}}">提现</a>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="cash">',
					'<strong>{{settleBalance}}</strong>',
					'<span>元</span>',
				'</div>',
				'<div class="bank">',
					'<span class="{{bankIcon}}"></span>',
					'<span class="name">{{bankComName}}</span>',
					'<span class="num">{{{bankAccountStr}}}</span>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<span class="shops pull-left">',
					'{{shopCount}}家店',
				'</span>',
				'{{# if isDetail }}',
					'<div class="btn-group pull-right visible-xs-inline-block">',
						'{{#each acts}}',
							'{{#if isFirst}}',
								'<button type="button" class="btn btn-info {{disableWithdraw}}" data-act="{{act}}">{{label}}</button>',
								'<button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">',
									'<span class="caret"></span>',
									'<span class="sr-only">Toggle Dropdown</span>',
								'</button>',
								'<ul class="dropdown-menu" role="menu">',
							'{{else}}',
								'<li><a href="javascript:void(0);" data-act="{{act}}" class="btn {{disabled}}">{{label}}</a></li>',
							'{{/if}}',
						'{{/each}}',
						'</ul>',
						
					'</div>',
				'{{else}}',
					'<a class="btn btn-link pull-right" data-href="{{path}}">详情&gt;</a>',
				'{{/if}}',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_card', tpl_account_card);

	var tpl_account_list = [
		'{{#with accountCard}}',
			'{{#each list}}',
			'<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">',
				'{{> accountCard}}',
			'</div>',
			'{{/each}}',
			// @NOTE: 新需求STORY #1074，任何权限的用户都不允许添加结算账户，所以屏蔽掉添加结算账户的片段
			// '<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">',
			// 	'{{> addAccountCard}}',
			// '</div>',
		'{{/with}}',
	].join('');
	TplLib.register('tpl_account_list', tpl_account_list);

	var tpl_withdraw_form = [
		'<div class="table-responsive">',
			'<table class="table table-striped table-bordered">',
				'<tbody>',
				'{{#each accountInfo}}',
					'<tr>',
						'<th>{{label}}</th>',
						'<td>{{{value}}}</td>',
					'</tr>',
				'{{/each}}',
				'</tbody>',
			'</table>',
		'</div>',
		'{{{warningText}}}',
		'<form class="form-horizontal {{formClz}}" role="form">',
			'<div class="form-group">',
				'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
				'<div class="{{clz}}">',
					'<div class="input-group">',
						'<span class="input-group-addon">￥</span>',
						'<input type="text" id="{{id}}" name="{{name}}" class="form-control" value="{{value}}" />',
						'<span class="input-group-addon">元</span>',
					'</div>',
				'</div>',
			'</div>',
		'</form>',
		'{{{noticeAcctountText}}}',
	].join('');
	TplLib.register('tpl_withdraw_form', tpl_withdraw_form);

	var tpl_addAccount_Card = [
		'<div class="panel panel-default ix-card bank-card create-account" data-btn-name="createAccount">',
			'<div class="panel-heading ix-card-header hidden">',
				'<h4 class="panel-title"></h4>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="x-mul-vertical-middle">',
					'<div class="item  x-v-m-out">',
						'<div class="x-v-m-in">',
							'<div class="ix-cross">',
								'<div class="x-cross-inner"></div>',
							'</div>',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<a class="btn btn-link pull-right" href="javascript:void(0);" data-href="{{path}}">添加账户</a>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_addAccount_Card', tpl_addAccount_Card);

	var tpl_accountMgr_layout = [
		'<nav class="account-nav">',
		'</nav>',
		'<section class="account-schema-box">',
		'</section>',
		  '<div class="navbar navbar-default account-tab">',
		  '</div>',
		'<section class="account-detail-box">',
		'</section>'
	].join('');
	TplLib.register('tpl_accountMgr_layout', tpl_accountMgr_layout);

	var tpl_account_schema = [
		'<div class="account-schema clearfix">',
			'{{#with accountCard}}',
				'{{> accountCard}}',
			'{{/with}}',
			'<div class="account-btns hidden-xs">',
				'<ul class="nav nav-pills pull-right" role="tablist">',
					'{{#each acts}}',
						'<li role="presentation"><a href="javascript:void(0);" class="btn {{clz}} {{disableWithdraw}} {{disabled}}" data-act="{{act}}">{{label}}</a></li>',
					'{{/each}}',
				'</ul>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_schema', tpl_account_schema);

	var tpl_account_detail = [
		'<div class="account-detail">',
			'<div class="well well-sm query-form">',
				'{{#with query}}',
					'{{> transaQueryForm}}',
				'{{/with}}',
			'</div>',
			'<div class="query-result">',
				'{{#with result}}',
					'{{> transaQueryResult}}',
				'{{/with}}',
			'</div>',
			'<div class="page-selection pull-right"></div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_detail', tpl_account_detail);


	var tpl_transaQuery_form = [
		'<form class="form-horizontal" role="">',
			'<div class="row">',
				'{{#each cols}}',
					'<div class="{{colClz}}">',
						'{{#each items}}',
							'{{#checkFormElementType type type="combo"}}',
								'<div class="form-group">',
									'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
									'<div class="{{clz}}">',
										'<select id="{{id}}" name="{{name}}" class="form-control"  data-type="{{type}}">',
											'{{#each options}}',
												'<option value="{{value}}" {{selected}}>{{label}}</option>',
											'{{/each}}',
										'</select>',
									'</div>',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="section"}}',
								'<div class="form-group section">',
									'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
									'{{#with min}}',
										'<div class="min-input {{clz}}">',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'</div>',
									'{{/with}}',
									'{{#with max}}',
										// '<div class="col-sm-1 hidden-xs hidden-sm"><span class="to-label">到</span></div>',
										'<div class="max-input {{clz}}">',
											'<span class="to-label">到</span>',
											'<div class="input-group">',
												'{{#if prefix}}',
													'<span class="input-group-addon">',
														'{{{prefix}}}',
													'</span>',
												'{{/if}}',
												'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
												'{{#if surfix}}',
													'<span class="input-group-addon">',
														'{{{surfix}}}',
													'</span>',
												'{{/if}}',
											'</div>',
										'</div>',
									'{{/with}}',
								'</div>',
							'{{/checkFormElementType}}',
							'{{#checkFormElementType type type="button"}}',
								'<button type="button" name="{{name}}" class="btn {{clz}}">{{{label}}}</button>',
							'{{/checkFormElementType}}',
						'{{/each}}',
					'</div>',
				'{{/each}}',
			'</div>',
		'</form>'
	].join('');
	TplLib.register('tpl_transaQuery_form', tpl_transaQuery_form);

	var tpl_transaQuery_result = [
		'<div class="table-responsive">',
			'<table class="table {{clz}}">',
				'<thead>',
					'{{#each thead}}',
						'<tr class="{{clz}}">',
							'{{#each cols}}',
								'<th class="{{clz}}" colspan="{{colspan}}" rowspan="{{rowspan}}">{{{label}}}</th>',
							'{{/each}}',
						'</tr>',
					'{{/each}}',
				'</thead>',
				'{{#if isEmpty}}',
					'<tbody>',
						'<tr>',
							'<td colspan="{{colCount}}"><p class="text-center">无结果</p></td>',
						'</tr>',
					'</tbody>',
				'{{else}}',
					'<tbody>',
						'{{#each rows}}',
							'<tr class="{{clz}}">',
								'{{#each cols}}',
									'<td class="{{clz}}">',
										'{{#chkColType type type="button"}}',
											'<a href="javascript:void(0);" class="{{btnClz}}" data-id="{{SUATransItemID}}" data-type="{{transType}}" data-orderid="{{orderID}}" data-orderkey="{{orderKey}}" >{{label}}</a>',
										'{{/chkColType}}',
										'{{#chkColType type type="text"}}',
											'<p data-value="{{value}}">{{{text}}}</p>',
										'{{/chkColType}}',
									'</td>',
								'{{/each}}',
							'</tr>',
						'{{/each}}',
					'</tbody>',
				'{{/if}}',
				'<tfoot>',
					'{{#each tfoot}}',
						'<tr class="{{clz}}">',
							'{{#each cols}}',
								'<th class="{{clz}}" colspan="{{colspan}}" rowspan="{{rowspan}}">',
									'<p data-value="{{value}}" >{{{text}}}</p>',
								'</th>',
							'{{/each}}',
						'</tr>',
					'{{/each}}',
				'</tfoot>',
			'</table>',
		'</div>'
	].join('');
	TplLib.register('tpl_transaQuery_result', tpl_transaQuery_result);

	var tpl_account_edit = [
		'<form class="form-horizontal {{formClz}}" role="form">',
			'{{#each items}}',
				'{{#checkFormElementType type type="combo"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<select id="{{id}}" name="{{name}}" {{disabled}} class="form-control"  data-type="{{type}}">',
								'{{#each options}}',
									'<option value="{{value}}" {{selected}}>{{label}}</option>',
								'{{/each}}',
							'</select>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="text"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#isInputGroup prefix surfix}}',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" {{disabled}} name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'{{else}}',
								'<input type="text" id="{{id}}" name="{{name}}" {{disabled}} class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
							'{{/isInputGroup}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="switcher"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'<input type="checkbox" id="{{id}}" name="{{name}}" {{disabled}} value="{{defaultVal}}" data-type="{{type}}" data-onLabel="{{onLabel}}" data-offLabel="{{offLabel}}" {{checked}} />',
						'</div>',
						'<p class="help-block {{helpClz}}">{{{help}}}</p>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="radiogrp"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#each options}}',
								'<label class="{{clz}}">',
									'<input type="radio" name="{{name}}" {{disabled}} id="{{id}}" value="{{value}}" {{checked}} />',
									'{{label}}',
								'</label>',
							'{{/each}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
			'{{/each}}',
		'</form>'
	].join('');
	TplLib.register('tpl_account_edit', tpl_account_edit);

	var tpl_account_query_shop = [
		'<div class="query-shop {{clz}}">',
			'<p class="title">',
				'{{label}}:<strong>{{title}}</strong>',
			'</p>',
			'<div class="query-box"></div>',
			'<div class="result-box"></div>',
		'</div>'
	].join('');
	TplLib.register('tpl_account_query_shop', tpl_account_query_shop);

	var tpl_orderpay_detail = [
		'<div class="row order-detail">',
			'<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">',
				'{{#each fieldsets}}',
					'{{log label}}',
					'{{#chkFieldType fieldType type="list"}}',
						'<h5>{{label}}{{{orderSubTypeLabel}}}</h5>',
						'<div class="row">',
							'{{#each fields}}',
								'{{log @key}}',
								'<div class="detail-item {{clz}}">',
									'<label>{{label}}:</label>',
									'<span>',
										'{{{value}}}',
									'</span>',
								'</div>',

							'{{/each}}',
						'</div>',
					'{{/chkFieldType}}',
					'{{#chkFieldType fieldType type="table"}}',
						'<h5>{{label}}</h5>',
						'<div class="table-responsive">',
							'<table class="table table-condensed table-hover table-striped">',
								'<thead>',
									'<tr>',
										'<th>名称</th>',
										'<th>类型</th>',
										'<th>价格</th>',
										'<th>份数</th>',
									'</tr>',
								'</thead>',
								'<tbody>',
									'{{#each categories}}',
										'<tr>',
											'<th colspan="4">',
												'{{foodCategoryName}}',
												'{{foodCategorySum}}',
											'</th>',
										'</tr>',
										'{{#each rows}}',
											'<tr>',
												'<td class="{{Indent}}">{{foodName}}</td>',
												'<td>{{foodUnit}}</td>',
												'<td>{{foodPrice}}</td>',
												'<td>{{foodAmount}}</td>',
											'</tr>',
										'{{/each}}',
									'{{/each}}',
								'</tbody>',
							'</table>',
						'</div>',
					'{{/chkFieldType}}',
				'{{/each}}',
			'</div>',
			// Modify: 根据最新指示，订单打印内容屏蔽掉
			// '<div class="col-xs-5 col-sm-5 col-md-4 col-lg-3">',
			// 	'{{#with printDetail}}',
			// 		'<h5>{{label}}{{{orderSubTypeLabel}}}</h5>',
			// 		'<p>',
			// 			'{{{content}}}',
			// 		'</p>',
			// 	'{{/with}}',
			// '</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_orderpay_detail', tpl_orderpay_detail);

	var tpl_fsmcustomer_detail = [
		'{{#with settleUnitDetail}}',
			'<h5>结算账户信息</h5>',
			'<div class="{{clz}} row settle-detail">',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">账户名称：</label>',
						'<span class="col-xs-12 col-sm-7">{{settleUnitName}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">结算时间：</label>',
						'<span class="col-xs-12 col-sm-7">{{transSuccessTime}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">交易类型：</label>',
						'<span class="col-xs-12 col-sm-7">{{transTypeLabel}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">交易金额：</label>',
						'<span class="col-xs-12 col-sm-7">{{transAmount}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">扣除佣金：</label>',
						'<span class="col-xs-12 col-sm-7">{{transSalesCommission}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">结算金额：</label>',
						'<span class="col-xs-12 col-sm-7">{{transAfterBalance}}元</span>',
					'</div>',
				'</div>',
			'</div>',
		'{{/with}}',
		'{{#with customerCard}}',
			'<h5>交易明细</h5>',
			'<div class="{{clz}} row customer-detail">',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">充值金额：</label>',
						'<span class="col-xs-12 col-sm-7">{{saveMoneyTotal}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员账户余额：</label>',
						'<span class="col-xs-12 col-sm-7">{{moneyBalance}}元</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员卡号：</label>',
						'<span  class="col-xs-12 col-sm-7">{{cardNO}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员手机号：</label>',
						'<span  class="col-xs-12 col-sm-7">{{customerMobile}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6">',
					'<div class="detail-item row">',
						'<label class="col-xs-12 col-sm-5">会员姓名：</label>',
						'<span  class="col-xs-12 col-sm-7">{{customerName}}</span>',
					'</div>',
				'</div>',
			'</div>',
		'{{/with}}',
	].join('');
	TplLib.register('tpl_fsmcustomer_detail', tpl_fsmcustomer_detail);

})(jQuery, window);