(function ($, window) {
	IX.ns("Hualala");
	var TplLib = Hualala.TplLib;

	var tpl_shop_filter = [
		'<div class="{{type}}">',
			'<span class="label">{{name}}</span>',
			'{{#each items}}',
				'<a class="btn btn-link {{focusClz}}" href="javascript:void(0);" data-{{type}}="{{code}}">',
					'{{name}}',
					'{{#if count}}',
						'<i class="num">({{count}})</i>',
					'{{/if}}',
				'</a>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_filter', tpl_shop_filter);

	var tpl_shop_query = [
		'<div class="shop-query {{clz}}">',
			'<div class="filter">',
				'{{#with shopCity}}',
				'{{> shopCity}}',
				'{{/with}}',
				// '{{> shopArea}}',
			'</div>',
			'<nav class="navbar navbar-default query" role="query">',
				'<div class="container-fluid">',
					'<div class="navbar-header">',
						'{{#with toggle}}',
						'{{> toggle}}',
						'{{/with}}',
						'<a class="navbar-brand" href="javascript:void(0);">查询店铺</a>',
					'</div>',
					'<div class="collapse navbar-collapse" id="shop_query">',
						'<div class="navbar-form navbar-left" role="search">',
							'<select class="hidden">',
								'{{#each optGrp}}',
									'<optgroup label="{{name}}">',
										'{{#each items}}',
											'<option value="{{code}}">{{name}}</option>',
										'{{/each}}',
									'</optgroup>',
								'{{/each}}',
							'</select>',
							'<div class="input-group">',
								'<input type="text" class="form-control" autocomplete="off" />',
								'<span class="input-group-btn">',
									'<button class="btn btn-default">查询</button>',
								'</span>',
							'</div>',
						'</div>',
						'{{#if needShopCreate}}',
							'<button class="btn btn-warning create-shop pull-right" style="margin-top:8px;">创建店铺</button>',
						'{{/if}}',
					'</div>',
				'</div>',
			'<nav>',
		'</div>',

		/*<div class="shop-query">',
			'<div class="filter">',
				'<div class="city">',
					'<span class="label">城市：</span>',
					'<a class="btn btn-link disabled">全部</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
				'</div>',
				'<div class="area">',
					'<span class="label">区域：</span>',
					'<a class="btn btn-link disabled">全部</a>',
					'<a class="btn btn-link">海淀</a>',
					'<a class="btn btn-link">朝阳</a>',
					'<a class="btn btn-link">大兴</a>',
					'<a class="btn btn-link">回龙观</a>',
					'<a class="btn btn-link">昌平</a>',
					'<a class="btn btn-link">龙泽</a>',
					'<a class="btn btn-link">顺义</a>',
				'</div>',
			'</div>',
			'<nav class="navbar navbar-default query" role="navigation">',
				'<div class="container-fluid">',
					'<div class="navbar-header">',
						'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#shop_query">',
							'<span class="sr-only">Toggle navigation</span>',
							'<span class="icon-bar"></span>',
							'<span class="icon-bar"></span>',
							'<span class="icon-bar"></span>',
						'</button>',
						'<a class="navbar-brand" href="javascript:void(0);">查询店铺</a>',
					'</div>',
					'<div class="collapse navbar-collapse" id="shop_query">',
						'<div class="navbar-form navbar-left" role="search">',
							'<div class="input-group">',
								'<input type="text" class="form-control" autocomplete="off" />',
								'<span class="input-group-btn">',
									'<button class="btn btn-default">查询</button>',
								'</span>',
							'</div>',
						'</div>',
						'<button class="btn btn-warning create-shop pull-right" style="margin-top:8px;">创建店铺</button>',
					'</div>',
				'</div>',
			'</nav>',
		'</div>*/
	].join('');
	TplLib.register('tpl_shop_query', tpl_shop_query);

	var tpl_shop_tags = [
		'<div class="tags">',
			'{{#each tags}}',
				'<span class="label {{clz}}" title="{{tag}}">{{tag}}</span>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_tags', tpl_shop_tags);

	var tpl_shop_list_item = [
		'<div class="shop-list-item col-xs-12 {{clz}} ">',
			'<div class="row shop-base-info">',
				'<div class="col-xs-6 col-sm-3 col-md-2">',
					'<h4>{{shopName}}</h4>',
				'</div>',
				'<div class="hidden-xs col-sm-4 col-md-7 ">',
					'<div class="account">',
						'<label class="account-label">结算账户：</label>',
						'<span class="account-name">{{accountName}}</span>',
					'</div>',
				'</div>',
				'<div class="col-xs-6 col-sm-5 col-md-3">',
					'<div class="switcher-wrapper pull-right">',
						'<label class="">店铺当前状态：</label>',
						'<input type="checkbox" name="{{switcherName}}" data-shop="{{shopID}}" {{shopOpen}} />',
					'</div>',
				'</div>',
			'</div>',
			'{{#each business}}',
			'<div class="row shop-business">',
				'<div class="col-xs-6 col-sm-3 col-md-2">',
					'<h4>',
						'<span class="{{icon}}"></span>',
						'{{name}}',
					'</h4>',
				'</div>',
				'<div class="col-xs-6 col-sm-2 col-md-2">',
					'<div class="switcher-wrapper">',
						'<input type="checkbox" name="{{switcherName}}" data-shop="{{shopID}}" data-business="{{type}}" {{open}} />',
					'</div>',
				'</div>',
				'<div class="col-xs-12 col-sm-6 col-md-7">',
					'<p>{{desc}}</p>',
				'</div>',
				'<div class="col-xs-12 col-sm-1 col-md-1">',
					'<button type="button" class="btn btn-default pull-right" data-shop="{{shopID}}" data-business="{{type}}">修改</button>',
				'</div>',
			'</div>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_list_item', tpl_shop_list_item);

	var tpl_shop_card = [
		'<div class="panel panel-default ix-card shop-card {{clz}}" >',
			'<div class="panel-heading ix-card-header">',
				'<h4 class="panel-title">{{name}}</h4>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="media">',
					'<a class="pull-left" href="javascript:void(0);">',
						'<img class="media-object" alt="{{name}}" src="{{img}}" />',
					'</a>',
					'<div class="media-body">',
						'{{> shopTag}}',
						'<address title="{{address}}">{{slugAddr}}</address>',
						'<div class="phone">{{tel}}</div>',
					'</div>',
					'<div class="btns pull-right">',
						'<a href="javascript:void(0);" class="btn btn-default shop-info" data-href="{{infoHref}}">',
							'修改店铺信息',
						'</a>',
						'<a href="javascript:void(0);" class="btn btn-default shop-menu" data-href="{{menuHref}}">',
							'菜谱管理',
						'</a>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<label>店铺当前状态：</label>',
				'<input type="checkbox" name="switcher" data-shop="{{id}}" class="shop-switch" {{checked}} />',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_card', tpl_shop_card);

	var tpl_shop_list = [
		'{{#with shopCard}}',
			'{{#each list}}',
			'<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">',
				'{{> shopCard}}',
			'</div>',
			'{{/each}}',
		'{{/with}}',
	].join('');
	TplLib.register('tpl_shop_list', tpl_shop_list);

	var tpl_shop_list_layout = [
		'<div class="shop-list">',
			'<div class="row shop-list-body">',
			'</div>',
			'<div class="shop-list-footer">',
				'<div class="page-selection pull-right"></div>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_list_layout', tpl_shop_list_layout);
})(jQuery, window);