(function ($, window) {
	IX.ns("Hualala");
	var TplLib = Hualala.TplLib;
	
	var tpl_set_shop_client_pwd = [
	'<form class="form-horizontal">',
		'<div class="form-group">',
			'<label class="col-sm-3 control-label">店铺账号:</label>',
			'<div class="col-sm-9">',
				'<p class="form-control-static">{{shopID}}</p>',
			'</div>',
		'</div>',
		'<div class="form-group has-feedback">',
			'<label for="shopClinetPwd" class="col-sm-3 control-label">登录密码:</label>',
			'<div class="col-sm-9">',
				'<input type="password" id="shopClinetPwd" name="shopClinetPwd"  class="form-control" />',
				'<i class="form-control-feedback glyphicon"></i>',
				'<small class="help-block"></small>',
			'</div>',
		'</div>',
		'<div class="checkbox col-sm-offset-3">',
			'<label for="showPwd" class="control-label">',
				'<input type="checkbox" id="showPwd" name="shopClinetPwd" />',
				'显示明文',
			'</label>',
		'</div>',
	'</form>'].join('');
	TplLib.register('tpl_set_shop_client_pwd', tpl_set_shop_client_pwd);

	var tpl_shop_info_head = [
	/*'<div class="bs-callout shop-info-head">',*/
		'<div class="fl">',
			'<span class="shop-name">{{shopName}}</span>',
			'<a href="{{shopUrl}}" target="_blank">查看网上店铺</a>',
			'<a href="{{shopListLink}}">切换店铺</a>',
			'<a id="resetPwd" href="javascript:;">设置代理程序密码</a>',
		'</div>',
		'<div class="shop-state">',
			'<label class="t-label">店铺当前状态：</label>',
			'<input type="checkbox" {{checked}} />',
		'</div>',
        '{{#if isSaasOpen}}',
        '{{else}}',
            '<div class="clearfix t-l">',
                '{{#if softName}}<span class="text-warning">该店铺已与{{softName}}打通</span>{{/if}}',
            '</div>',
        '{{/if}}',
	/*'</div>'*/].join('');
	TplLib.register('tpl_shop_info_head', tpl_shop_info_head);

	var tpl_shop_create = [
	'<div id="shopCreateWizard">',
		'<ul class="step-nav">',
			'<li><a href="#tab1" data-toggle="tab"><span class="label">1</span>基本信息</a></li>',
			'<li><a href="#tab2" data-toggle="tab"><span class="label">2</span>标注地图</a></li>',
			'<li><a href="#tab3" data-toggle="tab"><span class="label">3</span>创建成功</a></li>',
		'</ul>',
		'<div class="tab-content">',
			'<!-- 第一步 -->',
			'<form class="row tab-pane feed-back-out" id="tab1">',
				'<div class="col-sm-6 col-md-4 form-horizontal">',
					'<div class="form-group">',
						'<label for="shopName" class="col-sm-3 control-label">* 店铺名称</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="shopName" name="shopName"  class="form-control" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="cityID">* 所在城市</label>',
						'<div class="col-sm-8">',
							'<select id="cityID" name="cityID" class="form-control">',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="tel">* 店铺电话</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="tel" name="tel" class="form-control" placeholder="固定电话/手机号" title="多个号码用英文逗号隔开" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="address">* 店铺地址</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="address" name="address" class="form-control" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="PCCL">* 人均消费</label>',
						'<div class="col-sm-8">',
							'<input type="text" id="PCCL" name="PCCL" class="form-control" />',
						'</div>',
					'</div>',
				'</div>',
				'<div class="col-sm-6 col-md-4 form-horizontal">',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="operationMode">* 运营模式</label>',
						'<div class="col-sm-8">',
							'<select id="operationMode" name="operationMode" class="form-control"></select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-xs-12 col-sm-3 control-label" for="openingHours">* 营业时间</label>',
						'<div class="col-xs-8">',
							'<input type="text" id="openingHoursStart" name="openingHoursStart" class="form-control d-ib mr25"  placeholder="08:30" data-default-time="08:30" />',
							'<input type="text" id="openingHoursEnd" name="openingHoursEnd" class="form-control d-ib"  placeholder="21:30" data-default-time="21:30" />',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="areaID">* 地标</label>',
						'<div class="col-sm-8">',
							'<select id="areaID" name="areaID" class="form-control">',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="cuisineID1">* 菜系1</label>',
						'<div class="col-sm-8">',
							'<select id="cuisineID1" name="cuisineID1" class="form-control">',
								'<option value="">--请选择--</option>',
							'</select>',
						'</div>',
					'</div>',
					'<div class="form-group">',
						'<label class="col-sm-3 control-label" for="cuisineID2">菜系2</label>',
						'<div class="col-sm-8">',
							'<select id="cuisineID2" name="cuisineID2" class="form-control">',
								'<option value="">--不限--</option>',
							'</select>',
						'</div>',
					'</div>',
				'</div>',
				'<div id="uploadImg" class="col-sm-6 col-md-4">',
					'<span class="t-label">请上传店铺头图，不能大于10m<br />(根据餐厅特色上传环境图或菜品图)</span>',
					'<button class="btn btn-default v-t">上传图片</button><br />',
					'<img class="m-t" src="" alt="餐厅门头图" width="200" height="200" />',
				'</div>',
			'</form>',
			'<!-- 第二步 -->',
			'<div class="tab-pane map-wrap" id="tab2">',
				'<div class="map-search row">',
					'<div class="col-sm-4">',
						'<div class="input-group search-box map-search-box">',
							'<input class="form-control map-keyword" type="text" placeholder="搜索地图" />',
							'<span class="input-group-addon glyphicon glyphicon-search map-search-btn" title="搜索"></span>',
						'</div>',
					'</div>',
					'<div class="col-sm-3 map-help">您可拖动标注获取坐标</div>',
				'</div>',
				'<div class="map_canvas" id="mapCanvas"></div>',
				'<div class="map-result"></div>',
			'</div>',
			'<!-- 第三步 -->',
			'<div class="tab-pane t-c" id="tab3">',
				'<div class="d-ib t-l">',
					'<h4>',
						'<span class="glyphicon glyphicon-ok x-ico-suc"></span>',
						'恭喜！<span></span>创建成功！',
					'</h4>',
					'完成以下两个步骤，您的店铺就正式开通啦——',
					'<ul>',
						'<li>',
							'<a class="btn btn-success" href="{{pcClientPath}}" target="_blank">下载哗啦啦代理程序</a>',
							'上传菜品信息',
						'</li>',
						'<li>',
							'<a id="shopSettingLink" class="btn btn-success" href="">设置店铺功能</a>',
						'</li>',
						'<li>网上餐厅正式开通啦！</li>',
					'</ul>',
				'</div>',
			'</div>',
			'</div>',
		'<div class="step-action">',
			'<button type="button" class="btn btn-default prev-step">上一步</button>',
			'<button id="nextStep" type="button" class="btn btn-warning">下一步</button>',
		'</div>',
	'</div>'].join('');
	TplLib.register('tpl_shop_create', tpl_shop_create);
	
	var tpl_shop_info = [
	'<form class="row shop-info feed-back-out read-mode">',
		'<div class="col-sm-6 col-lg-3 form-horizontal">',
			'<div class="form-group">',
				'<label for="shopName" class="col-sm-3 control-label">店铺名称</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{shopName}}</p>',
					'<input type="text" id="shopName" name="shopName"  class="form-control" value="{{shopName}}" />',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="cityID">所在城市</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{cityName}}</p>',
					'<select id="cityID" name="cityID" class="form-control">',
					'</select>',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="tel">店铺电话</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{tel}}</p>',
					'<input type="text" id="tel" name="tel" class="form-control" placeholder="固定电话/手机号" title="多个号码用英文逗号隔开" value="{{tel}}" />',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="address">店铺地址</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{address}}</p>',
					'<input type="text" id="address" name="address" class="form-control" value="{{address}}" />',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="PCCL">人均消费</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{PCCL}}</p>',
					'<input type="text" id="PCCL" name="PCCL" class="form-control" value="{{PCCL}}" />',
				'</div>',
			'</div>',
		'</div>',
		'<div class="col-sm-6 col-lg-3 form-horizontal">',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="operationMode">运营模式</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{operationModeName}}</p>',
					'<select id="operationMode" name="operationMode" class="form-control"></select>',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-xs-12 col-sm-3 control-label" for="openingHours">营业时间</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{openingHours}}</p>',
					'<input type="text" id="openingHoursStart" name="openingHoursStart" class="form-control d-ib mr25"  placeholder="08:30" data-default-time="08:30" value="{{openingHoursStart}}" />',
					'<input type="text" id="openingHoursEnd" name="openingHoursEnd" class="form-control d-ib"  placeholder="21:30" data-default-time="21:30"  value="{{openingHoursEnd}}" />',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="areaID">地标</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{areaName}}</p>',
					'<select id="areaID" name="areaID" class="form-control">',
						'<option value="">--请选择--</option>',
					'</select>',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label" for="cuisineID1">菜系1</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{cuisineName1}}</p>',
					'<select id="cuisineID1" name="cuisineID1" class="form-control">',
						'<option value="">--请选择--</option>',
					'</select>',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-3 control-label no-require" for="cuisineID2">菜系2</label>',
				'<div class="col-sm-9">',
					'<p class="form-control-static">{{cuisineName2}}</p>',
					'<select id="cuisineID2" name="cuisineID2" class="form-control">',
						'<option value="">--不限--</option>',
					'</select>',
				'</div>',
			'</div>',
		'</div>',
		'<div id="uploadImg" class="col-sm-6 col-lg-3 t-r">',
			'<img class="mb-12" src="" alt="餐厅门头图" width="200" height="200" /><br />',
			'<a href="javascript:;">修改门头图</a>',
		'</div>',
		'<div class="col-sm-6 col-lg-3">',
			'<div class="input-group search-box">',
				'<input class="form-control map-keyword" type="text" placeholder="搜索地图" />',
				'<span class="input-group-addon glyphicon glyphicon-search map-search-btn" title="搜索"></span>',
			'</div>',
			'<div class="map_canvas" id="mapCanvas"></div>',
			'<div class="map-result mb-12"></div>',
			'<p class="t-r mb50"><a id="remarkMap" href="javascript:;">重新标记</a></p>',
		'</div>',
		'<div class="step-action">',
			'<button id="editBtn" class="btn btn-warning">修改</button>',
			'<button id="saveBtn" class="btn btn-warning">保存</button>',
		'</div>',
	'</form>'].join('');
	TplLib.register('tpl_shop_info', tpl_shop_info);
	
	var tpl_shop_menu = [
	'<div class="shop-menu">',
		'<div id="foodClassBox" class="panel panel-default food-class"></div>',
		'<form id="foodSearch" class="panel panel-default form-inline food-search">',
			'<div class="form-group">',
				'<select id="takeawayTag" class="form-control">',
					'<option value="">全部菜品</option>',
					'<option value="0">堂食菜品</option>',
					'<option value="1">外卖菜品</option>',
				'</select>',
				'<label><input type="checkbox" id="isSpecialty" value=""/> 招牌</label>',
				'<label><input type="checkbox" id="isRecommend" /> 推荐</label>',
				'<label><input type="checkbox" id="isNew" /> 新品</label>',
				'<label><input type="checkbox" id="isSetFood" /> 套餐</label>',
				'<label><input type="checkbox" id="isDiscount" /> 打折</label>',
				'<label><input type="checkbox" id="foodIsActive" /> 启用菜品</label>',
				'<label><input type="checkbox" id="isHasImage" /> 无图</label>',
				//'<span class="input-group search-box">',
					'<select id="foodName" class="form-control"></select>',
					//'<span id="btnSearchFood" class="input-group-addon glyphicon glyphicon-search" title="搜索"></span>',
				//'</span>',
			'</div>',
		'</form>',
		'<div id="foodSearchInfo">相关结果 (<span></span>)</div>',
		'<table class="tbl-foods">',
			'<thead>',
				'<tr>',
					'<th width="92px">菜品图片</th>',
					'<th width="120px">名称</th>',
					'<th width="120px">分类名称</th>',
					'<th>规格及单价 (<em>会员价</em><b>售价</b><span>原价</span>)</th>',
					'<th width="">打折</th>',
					'<th width="">是否外送</th>',
					'<th width="">打包费(元)</th>',
					'<th width="">是否在售</th>',
					'<th width="">排序</th>',
					'<th width="200px"></th>',
				'</tr>',
			'</thead>',
			'<tbody></tbody>',
		'</table>',
	'</div>'].join('');
	TplLib.register('tpl_shop_menu', tpl_shop_menu);
    
    var tpl_food_name = [
        '<option value=""></option>',
        '{{#each classifiedFoods}}',
            '<optgroup label="{{foodCategoryName}}">',
                '{{#each foods}}',
                    '<option value="{{foodID}}">{{foodName}}</option>',
                '{{/each}}',
            '</optgroup>',
        '{{/each}}',
    ].join(',');
    TplLib.register('tpl_food_name', tpl_food_name);
	
	var tpl_food = [
	'{{#each foods}}',
		'<tr class="{{first.topBorder}} {{last.BottomBorder}}" data-id="{{foodID}}" data-cid="{{foodCategoryID}}" data-sortindex="{{foodSortIndex}}">',
			'<td><img src="{{imgSrc}}" /></td>',
			'<td class="t-l">{{foodName}}{{{adsIco}}}</td>',
			'<td>{{foodCategoryName}}</td>',
			'<td>',
			'{{#each units}}',
				'<p><span>{{unit}}</span><em>{{vipPrice}}</em><b>{{prePrice}}</b><i>{{price}}</i></p>',
			'{{/each}}',
			'</td>',
			'<td><span class="glyphicon {{discountIco}}"></span></td>',
			'<td><span class="glyphicon {{takeawayIco}}"></span></td>',
			'<td><b>{{takeoutPackagingFee}}</b></td>',
			'<td><span class="glyphicon {{activeIco}}"></span></td>',
			'<td>',
                '<a href="javascript:{}" title="移到顶部" class="glyphicon glyphicon-arrow-up sort-top {{first.upDisabled}}"></a>',
                '<a href="javascript:{}" title="上移" class="glyphicon glyphicon-arrow-up ml-6 sort-up {{first.upDisabled}}"></a>',
                '<a href="javascript:{}" title="下移" class="glyphicon glyphicon-arrow-down ml-6 sort-down {{last.downDisabled}}"></a>',
                '<a href="javascript:{}" title="移到底部" class="glyphicon glyphicon-arrow-down ml-6 sort-bottom {{last.downDisabled}}"></a>',
            '</td>',
			'<td>',
				'<button class="btn btn-default">修改</buttion>',
				'{{#if ../isSaasOpen}}',
				'<button class="m-l btn btn-default">删除</buttion>',
				'{{/if}}',
			'</td>',
		'</tr>',
	'{{/each}}'].join('');
	TplLib.register('tpl_food', tpl_food);
    
    var tpl_edit_food = [
    '<ul class="nav nav-tabs" role="tablist">',
        '<li class="active"><a href="#foodBasicInfo" data-toggle="tab">基本信息</a></li>',
        '<li><a href="#foodDesc" data-toggle="tab">图文详情</a></li>',
    '</ul>',
    '<div class="tab-content">',
        '<div class="tab-pane active fade in" id="foodBasicInfo">',
            '<form class="form-food">',
                '<div>',
                    '<span>名称</span>',
                    '<span name="foodName">{{foodName}}</span>',
                '</div>',
                '<div>',
                    '<span>图标</span>',
                    '<label>',
                        '<i class="ico-food ico-zhao">招</i>',
                        '<input type="radio" name="foodIco" value="isSpecialty" />',
                        '招牌菜',
                    '</label>',
                    '<label>',
                        '<i class="ico-food ico-jian">荐</i>',
                        '<input type="radio" name="foodIco" value="isRecommend" />',
                        '推荐菜',
                    '</label>',
                    '<label>',
                        '<i class="ico-food ico-xin">新</i>',
                        '<input type="radio" name="foodIco" value="isNew" />',
                        '新菜 &nbsp;',
                    '</label>',
                    '<label class="active">',
                        '<input type="radio" name="foodIco" value="none" checked />',
                        '无',
                    '</label>',
                '</div>',
                '<div>',
                    '<span>辣度</span>',
                    '<label>',
                        '<img src="{{hotTag1}}" />',
                        '<input type="radio" name="hotTag" value="1" />',
                        '微辣',
                    '</label>',
                    '<label>',
                        '<img src="{{hotTag2}}" />',
                        '<input type="radio" name="hotTag" value="2" />',
                        '中辣',
                    '</label>',
                    '<label>',
                        '<img src="{{hotTag3}}" />',
                        '<input type="radio" name="hotTag" value="3" />',
                        '重辣',
                    '</label>',
                    '<label class="active">',
                        '<input type="radio" name="hotTag" value="0" checked />',
                        '无',
                    '</label>',
                '</div>',
                '<div>',
                    '<span>是否外送</span>',
                    '<label>',
                        '<input type="radio" name="takeawayTag" value="0" />',
                        '不外送',
                    '</label>',
                    '<label class="active">',
                        '<input type="radio" name="takeawayTag" value="1" checked />',
                        '可外送',
                    '</label>',
                    '<label>',
                        '<input type="radio" name="takeawayTag" value="2" />',
                        '仅外送',
                    '</label>',
                '</div>',
                '<div>',
                    '<span>是否打折</span>',
                    '<label>',
                        '<input type="radio" name="isDiscount" value="1" />',
                        '打折',
                    '</label>',
                    '<label class="active">',
                        '<input type="radio" name="isDiscount" value="0" checked />',
                        '不打折',
                    '</label>',
                '</div>',
                '<div>',
                    '<span>是否在售</span>',
                    '<label class="active">',
                        '<input type="radio" name="isActive" value="1" checked />',
                        '可售',
                    '</label>',
                    '<label>',
                        '<input type="radio" name="isActive" value="0" />',
                        '停售',
                    '</label>',
                '</div>',
                '<div class="form-group">',
                    '<span>起售份数</span>',
                    '<input type="text" name="minOrderCount" class="form-control" value="{{minOrderCount}}" />',
                '</div>',
                '<div class="form-group taste-list">',
                    '<span>口味</span>',
                    '<div>',
                        '<input type="text" name="tasteList" class="form-control" placeholder="多个口味用英文逗号“,”隔开" value="{{tasteList}}" maxlength="300" />',
                    '</div>',
                '</div>',
                '<div class="form-group taste-list">',
                    '<span>作法</span>',
                    '<div>',
                        '<input type="text" name="makingMethodList" class="form-control" placeholder="多个作法用英文逗号“,”隔开" value="{{makingMethodList}}" maxlength="500" />',
                    '</div>',
                '</div>',
            '</form>',
            '<div class="food-pic">',
                '<div>',
                    '<img src="{{foodPic}}" alt="菜品图片" width="200px" />',
                    '<span>上传中 . . .</span>',
                '</div>',
                '<label class="btn-link m-t">修改图片</label>',
            '</div>',
        '</div>',
        '<div class="tab-pane fade" id="foodDesc">',
            '<script type="text/plain" id="foodDescEditor" style="height: 300px"></script>',
        '</div>',
    '</div>'
    ].join('');
    TplLib.register('tpl_edit_food', tpl_edit_food);

	var tpl_shop_filter = [
		'<div class="{{type}}">',
			'<span class="label">{{name}}</span>',
			'{{#each items}}',
				'<a class="btn btn-link {{focusClz}}" href="javascript:void(0);" data-{{type}}="{{code}}">',
					'{{name}}',
					'{{#if count}}',
						'<i class="num">({{count}})</i>',
					'{{/if}}',
				'</a>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_filter', tpl_shop_filter);

	var tpl_shop_query = [
		'<div class="shop-query {{clz}}">',
			'<div class="filter">',
				'{{#with shopCity}}',
				'{{> shopCity}}',
				'{{/with}}',
				// '{{> shopArea}}',
			'</div>',
			'<nav class="navbar navbar-default query" role="query">',
				'<div class="container-fluid">',
					'<div class="navbar-header">',
						'{{#with toggle}}',
						'{{> toggle}}',
						'{{/with}}',
						'<a class="navbar-brand" href="javascript:void(0);">查询店铺</a>',
					'</div>',
					'<div class="collapse navbar-collapse" id="shop_query">',
						'<div class="navbar-form navbar-left" role="search">',
							// '<select class="">',
							// 	'{{#each optGrp}}',
							// 		'<optgroup label="{{name}}">',
							// 			'{{#each items}}',
							// 				'<option value="{{code}}">{{name}}</option>',
							// 			'{{/each}}',
							// 		'</optgroup>',
							// 	'{{/each}}',
							// '</select>',
							// '<div class="input-group">',
							// 	'<input type="text" class="form-control" autocomplete="off" />',
							// 	'<span class="input-group-btn">',
							// 		'<button class="btn btn-default">查询</button>',
							// 	'</span>',
							// '</div>',
							'<select class="chosen-select-no-results"  style="width:200px;">',
								'<option value=""></option>',
								'{{#each optGrp}}',
									'<optgroup label="{{name}}">',
										'{{#each items}}',
											'<option value="{{code}}">{{name}}</option>',
										'{{/each}}',
									'</optgroup>',
								'{{/each}}',
							'</select>',
							'<button class="btn btn-default query-btn">查询</button>',
							
						'</div>',
						'{{#if needShopCreate}}',
							'<button class="btn btn-warning create-shop pull-right" style="margin-top:8px;" data-btn-name="createShop">创建店铺</button>',
						'{{/if}}',
					'</div>',
				'</div>',
			'</nav>',
		'</div>',

		/*<div class="shop-query">',
			'<div class="filter">',
				'<div class="city">',
					'<span class="label">城市：</span>',
					'<a class="btn btn-link disabled">全部</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
					'<a class="btn btn-link ">北京<i class="num">(10)</i></a>',
					'<a class="btn btn-link">上海</a>',
					'<a class="btn btn-link">广州</a>',
					'<a class="btn btn-link">重庆</a>',
					'<a class="btn btn-link">深圳</a>',
					'<a class="btn btn-link">柳州</a>',
					'<a class="btn btn-link">天津</a>',
				'</div>',
				'<div class="area">',
					'<span class="label">区域：</span>',
					'<a class="btn btn-link disabled">全部</a>',
					'<a class="btn btn-link">海淀</a>',
					'<a class="btn btn-link">朝阳</a>',
					'<a class="btn btn-link">大兴</a>',
					'<a class="btn btn-link">回龙观</a>',
					'<a class="btn btn-link">昌平</a>',
					'<a class="btn btn-link">龙泽</a>',
					'<a class="btn btn-link">顺义</a>',
				'</div>',
			'</div>',
			'<nav class="navbar navbar-default query" role="navigation">',
				'<div class="container-fluid">',
					'<div class="navbar-header">',
						'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#shop_query">',
							'<span class="sr-only">Toggle navigation</span>',
							'<span class="icon-bar"></span>',
							'<span class="icon-bar"></span>',
							'<span class="icon-bar"></span>',
						'</button>',
						'<a class="navbar-brand" href="javascript:void(0);">查询店铺</a>',
					'</div>',
					'<div class="collapse navbar-collapse" id="shop_query">',
						'<div class="navbar-form navbar-left" role="search">',
							'<div class="input-group">',
								'<input type="text" class="form-control" autocomplete="off" />',
								'<span class="input-group-btn">',
									'<button class="btn btn-default">查询</button>',
								'</span>',
							'</div>',
						'</div>',
						'<button class="btn btn-warning create-shop pull-right" style="margin-top:8px;">创建店铺</button>',
					'</div>',
				'</div>',
			'</nav>',
		'</div>*/
	].join('');
	TplLib.register('tpl_shop_query', tpl_shop_query);

	var tpl_shop_tags = [
		'<div class="tags">',
			'{{#each tags}}',
				'<span class="label {{clz}}" title="{{tag}}">{{tag}}</span>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_tags', tpl_shop_tags);

	var tpl_shop_list_item = [
		'<div class="shop-list-item col-xs-12 {{clz}} ">',
			'<div class="row shop-base-info">',
				'<div class="col-xs-6 col-sm-3 col-md-2">',
					'<h4>{{shopName}}</h4>',
				'</div>',
				'<div class="hidden-xs col-sm-4 col-md-7 ">',
					'<div class="account">',
						'<label class="account-label">结算账户：</label>',
						'<span class="account-name">{{settleName}}</span>',
						'{{#if hideAccount}}',
							'{{#with btn}}',
								'<a href="javascript:void(0);" class=" {{clz}}" data-id="{{../settleID}}" data-shop="{{../shopID}}">{{label}}</a>',
							'{{/with}}',
						'{{else}}',
						'{{/if}}',
						
					'</div>',
				'</div>',
				'<div class="col-xs-6 col-sm-5 col-md-3">',
					'<div class="switcher-wrapper pull-right">',
						'<label class="">店铺当前状态：</label>',
						'<input type="checkbox" name="{{switcherName}}" data-shop="{{shopID}}" {{shopOpen}} />',
					'</div>',
				'</div>',
			'</div>',
			'{{#each business}}',
			'<div class="row shop-business">',
				'<div class="col-xs-6 col-sm-3 col-md-2">',
					'<h4>',
						'<span class="{{icon}}"></span>',
						'{{label}}',
					'</h4>',
				'</div>',
				'<div class="col-xs-6 col-sm-2 col-md-2">',
					'<div class="switcher-wrapper">',
						'<input type="checkbox" name="{{switcherName}}" data-shop="{{shopID}}" data-business="{{type}}" data-business-id="{{id}}" {{open}} />',
					'</div>',
				'</div>',
				'<div class="col-xs-12 col-sm-5 col-md-6">',
					'<p class="desc">{{desc}}</p>',
				'</div>',
				'<div class="col-xs-12 col-sm-2 col-md-2">',
					'<button type="button" class="btn btn btn-default  dowloadhref pull-left {{hide}}" name="download_link" data-shop="{{shopID}}"   data-business-id="{{id}}">桌台码下载</button>',
					'<button type="button" class="btn btn-default pull-right {{hideBtn}}" name="business_edit" data-shop="{{shopID}}" data-business="{{type}}"  data-business-id="{{id}}" data-serviceFeatures="{{serviceFeatures}}">修改</button>',
				'</div>',
			'</div>',
			'{{/each}}',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_list_item', tpl_shop_list_item);

	var tpl_shop_card = [
		'<div class="panel panel-default ix-card shop-card {{clz}}" >',
			'<div class="panel-heading ix-card-header">',
				'<h4 class="panel-title">{{name}}</h4>',
			'</div>',
			'<div class="panel-body ix-card-body">',
				'<div class="media">',
					'<a class="media-left" href="javascript:void(0);">',
						'<img class="media-object" alt="{{name}}" src="{{img}}" />',
					'</a>',
					'<div class="media-body">',
						'{{> shopTag}}',
						'<address title="{{address}}">{{slugAddr}}</address>',
						'<div class="phone">{{tel}}</div>',
					'</div>',
					'<div class="btns">',
						'<span>店铺ID：{{shopID}}</span>',
						'<a href="javascript:void(0);" class="btn btn-default shop-info pull-right" data-href="{{infoHref}}">',
							'管理店铺信息',
						'</a>',
						// '<a href="javascript:void(0);" class="btn btn-default shop-menu" data-href="{{menuHref}}">',
						// 	'菜谱管理',
						// '</a>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="panel-footer ix-card-footer">',
				'<label>店铺当前状态：</label>',
				'<input type="checkbox" name="switcher" data-shop="{{id}}" class="shop-switch" {{checked}} />',
				'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_card', tpl_shop_card);

	var tpl_shop_list = [
		'{{#with shopCard}}',
			'{{#each list}}',
			'<div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">',
				'{{> shopCard}}',
			'</div>',
			'{{/each}}',
		'{{/with}}',
		'{{#with shopItem}}',
			'{{#each list}}',
				'{{> shopItem}}',
			'{{/each}}',
		'{{/with}}',
		'{{#with shopTable}}',
			'{{> shopTable}}',
		'{{/with}}'
	].join('');
	TplLib.register('tpl_shop_list', tpl_shop_list);

	var tpl_shop_table = [
		'<div class="col-xs-12 table-responsive">',
			'<table class="table">',
				'<thead>',
					'<tr>',
						'<th>城市</th>',
						'<th>店铺ID</th>',
						'<th>店铺名称</th>',
					'</tr>',
				'</thead>',
				'{{#if isEmpty}}',
					'<tbody>',
						'<tr>',
							'<td colspan="{{colCount}}"><p class="text-center">无结果</p></td>',
						'</tr>',
					'</tbody>',
				'{{else}}',
					'<tbody>',
						'{{#each rows}}',
							'<tr class="{{clz}}">',
								'<td class="">',
									'{{city}}',
								'</td>',
								'<td class="">',
									'{{id}}',
								'</td>',
								'<td class="">',
									'{{name}}',
								'</td>',
							'</tr>',
						'{{/each}}',
					'</tbody>',
				'{{/if}}',
			'</table>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_table', tpl_shop_table);

	var tpl_shop_list_layout = [
		'<div class="shop-list">',
			'<div class="row shop-list-body">',
			'</div>',
			'<div class="shop-list-footer clearfix">',
				'<div class="page-selection pull-right"></div>',
			'</div>',
		'</div>'
	].join('');
	TplLib.register('tpl_shop_list_layout', tpl_shop_list_layout);

	var tpl_shop_service_form_layout = [
		'<form class="form-horizontal {{formClz}}" role="form">',
			'{{#each items}}',
				'{{#checkFormElementType type type="combo"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<select id="{{id}}" name="{{name}}" class="form-control"  data-type="{{type}}">',
								'{{#each options}}',
									'<option value="{{value}}" {{selected}}>{{label}}</option>',
								'{{/each}}',
							'</select>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="text"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#isInputGroup prefix surfix}}',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'{{else}}',
								'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
							'{{/isInputGroup}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="switcher"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'<input type="checkbox" id="{{id}}" name="{{name}}" value="{{defaultVal}}" data-type="{{type}}" data-onLabel="{{onLabel}}" data-offLabel="{{offLabel}}" {{checked}} />',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="section"}}',
					'<div class="form-group section">',
						'<label for="{{id}}" class="{{labelClz}}">{{#if choice}}{{{choice}}}{{/if}}{{label}}</label>',
						'{{#with min}}',
							'<div class="min-input {{clz}}">',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'</div>',
						'{{/with}}',
						'{{#with max}}',
							// '<div class="col-sm-1 hidden-xs hidden-sm"><span class="to-label">到</span></div>',
							'<div class="max-input {{clz}}">',
								'<span class="to-label hidden-xs hidden-sm">到</span>',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}"  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'</div>',
						'{{/with}}',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="hidden"}}',
					'<input type="hidden" id="{{id}}" name="{{name}}" value="{{value}}" />',
				'{{/checkFormElementType}}',
			'{{/each}}',
		'</form>'
	].join('');
	TplLib.register('tpl_shop_service_form_layout', tpl_shop_service_form_layout);

	var tpl_shop_modal_btns = [
		'{{#each btns}}',
			'<button type="button" class="btn {{clz}}" name="{{name}}" data-loading-text="{{loadingText}}" autocomplete="off">{{label}}</button>',
		'{{/each}}'
	].join('');
	TplLib.register('tpl_shop_modal_btns', tpl_shop_modal_btns);

	// 闪吃业务描述
	var tpl_shop_justeat_desc = [
		'{{{servicePeriods}}}',
		'{{{holidayFlag}}}',
		'{{{minAmount}}}',
		'{{{advanceTime}}}',
		'{{{noticeTime}}}',
		'{{{reserveTableTime}}}',
		'{{{reserveTableDesc}}}'
	].join('');
	TplLib.register('tpl_shop_justeat_desc', tpl_shop_justeat_desc);

	// 店内自助业务描述
	var tpl_shop_spotorder_desc = [

		'{{#if isDinner}}',
			// 正餐
			'{{{supportCommitToSoftware}}}',
			// '{{{payMethodAtShop}}}',
			'{{{checkSpotOrder}}}',
			'{{{payBeforeCommit}}}',
		'{{else}}',
			// 快餐
			'{{{supportCommitToSoftware}}}',
			'{{{fetchFoodMode}}}',
		'{{/if}}'
	].join('');
	TplLib.register('tpl_shop_spotorder_desc', tpl_shop_spotorder_desc);

	// tpl_shop_commonreserve_desc
	var tpl_shop_commonreserve_desc = [
		'{{{advanceTime}}}',
		'{{{noticeTime}}}',
		'{{{minAmount}}}',
		'{{{reserveTableTime}}}',
		'{{{reserveTableDesc}}}',
		'{{{payMethod}}}'
	].join('');
	TplLib.register('tpl_shop_commonreserve_desc', tpl_shop_commonreserve_desc);

	var tpl_shop_takeaway_desc = [
		'{{{servicePeriods}}}', '{{{holidayFlag}}}', '{{{noticeTime}}}', '{{{takeawayDeliveryTime}}}',
		'{{{minAmount}}}','{{{serviceAmount}}}','{{{freeServiceAmount}}}','{{{takeawayScope}}}','{{{payMethod}}}'
	].join('');
	TplLib.register('tpl_shop_takeaway_desc', tpl_shop_takeaway_desc);

	var tpl_shop_takeout_desc = [
		'{{{servicePeriods}}}','{{{holidayFlag}}}','{{{advanceTime}}}','{{{noticeTime}}}','{{{minAmount}}}','{{{payMethod}}}'
	].join('');
	TplLib.register('tpl_shop_takeout_desc', tpl_shop_takeout_desc);

    var tpl_query_form = [
        '<div class="well well-sm query-form">',
            '<form class="form-horizontal">',
                '<div class="row">',
                    '<div class="col-md-4">',
                        '<div class="form-group">',
                            '<label class="col-md-4 control-label">{{queryLabel}}</label>',
                            '<div class="col-md-8">',
                                '<input type="text" name="{{queryName}}" class="form-control">',
                            '</div>',
                        '</div>',
                    '</div>',
                    '<div class="col-md-2">',
                        '<button class="btn btn-warning" name="search">查询</button>',
                    '</div>',
                    '<div class="col-md-2 pull-right">',
                        '<button class="btn btn-warning" name="{{addBtnName}}">{{addBtnLabel}}</button>',
                    '</div>',
                '</div>',
            '</form>',
        '</div>'
    ].join('');
    TplLib.register('tpl_query_form', tpl_query_form);

    var tpl_edit_member = [
        '<div>',
            '<form class="form-horizontal form-member">',
                '<div class="pull-left col-md-6">',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">员工编码*&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="empCode" class="form-control" value="{{empCode}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">员工姓名*&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="empName" class="form-control" value="{{empName}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">身份证号*&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="IDCard" class="form-control" value="{{IDCard}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">手机号码*&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="empMobile" class="form-control" value="{{empMobile}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">职位名称*&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="positionName" class="form-control" value="{{positionName}}">',
                        '</div>',
                    '</div>',
                    '{{#if empKey}}',
                    '{{else}}',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">员工密码*&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="password" name="localPosLoginPWD" class="form-control" value="{{localPosLoginPWD}}">',
                        '</div>',
                    '</div>',
                    '{{/if}}',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">员工卡号&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="empCardNo" class="form-control" value="{{empCardNo}}">',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="pull-right col-md-6">',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">邮箱地址&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="empEmail" class="form-control" value="{{empEmail}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">最大折扣率&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="maxDiscountRate" class="form-control" value="{{maxDiscountRate}}">',
							'<span class="help-block">提醒：折扣率为0-1的数字且小数点后最多为两位，如0.88代表8.8折</span>',
						'</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">点菜器编号&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="padNo" class="form-control" value="{{padNo}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">最大免除金额&nbsp;</label>',
                        '<div class="col-md-8">',
                            '<input type="text" name="maxFreeAmount" class="form-control" value="{{maxFreeAmount}}">',
                        '</div>',
                    '</div>',
                    '<div class="form-group">',
                        '<label class="col-sm-4 control-label">员工照片&nbsp;</label>',
                        '<div class="food-pic col-md-6">',
                            '<div>',
                            '{{#if photoImage}}',
                            '<img src="{{photoImage}}" alt="员工照片" width="120px" />',
                            '{{else}}',
                            '<img src="./asset/img/food_bg.png" alt="员工照片" width="120px" />',
                            '{{/if}}',
                            '<span>上传中 . . .</span>',
                            '</div>',
                            '<label class="btn-link m-t">上传照片</label>',
                            '<div class="m-t warning text-warning">图片建议尺寸120*120</div>',
                        '</div>',
                    '</div>',
                '</div>',
                '<div class="form-remark form-group">',
                    '<label class="col-sm-2 control-label">人员备注说明</label>',
                    '<div class="col-sm-8">',
                        '<textarea class="form-control" name="empRemark" maxlength="500">{{empRemark}}</textarea>',
                    '</div>',
                '</div>',
            '</form>',
        '</div>'
    ].join('');
    TplLib.register('tpl_edit_member', tpl_edit_member);

    var tpl_reset_password = [
        '<form class="form-horizontal form-reset">',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label">新密码*&nbsp;</label>',
                '<div class="col-md-8">',
                    '<input type="password" name="empPWD" class="form-control">',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-3 control-label"></label>',
                '<div class="col-md-8">',
                    '<label class="control-label"><input type="checkbox" name="displayPassword">&nbsp;&nbsp;显示明文</label>',
                '</div>',
            '</div>',
        '</form>'
    ].join('');
    Hualala.TplLib.register('tpl_reset_password', tpl_reset_password);

    var tpl_edit_role = [
        '<form class="form-horizontal role-right">',
			'<h5 class="page-header">店员：{{empName}}</h5>',
            '<div class="form-group roles">',
                '<label class="title">角色</label>',
                '<div class="clearfix border">',
                    '{{#each roles}}',
                        '<label><input type="checkbox" {{checked}} name="role" data-key="{{roleID}}" />&nbsp;{{roleName}}</label>',
                    '{{/each}}',
                '</div>',
            '</div>',
            '<div class="form-group rights">',
                '<label class="title">权限</label>',
                '<div class="clearfix border">',
                '{{#each rightGroup}}',
                    '<div class="form-group">',
                        '<label class="control-label">{{@key}}</label>',
                        '<div>',
                            '{{#each this}}',
                                '<label><input type="checkbox" {{checked}} name="right" data-key="{{rightID}}" disabled />&nbsp;{{rightName}}</label>',
                            '{{/each}}',
                        '</div>',
                    '</div>',
                '{{/each}}',
            '</div>',
            '</div>',
        '</form>',
    ].join('');
    Hualala.TplLib.register('tpl_edit_role', tpl_edit_role);

    var tpl_chosen = [
        '<option value=""></option>',
        '{{#each groups}}',
        '<optgroup label="{{groupName}}">',
        '{{#each options}}',
        '<option value="{{value}}">{{label}}</option>',
        '{{/each}}',
        '</optgroup>',
        '{{/each}}',
    ].join(',');
    TplLib.register('tpl_chosen', tpl_chosen);

    //submit file unicode
    var tpl_table_query = [
        '<div class="panel panel-default food-class clearfix">',
            '<div id="tableAreaBox" class="col-md-11">',
            '</div>',
            '<div class="col-md-1 pull-right">',
                '<a class="btn btn-warning" href="{{areaLink}}">区域管理</a>',
            '</div>',
        '</div>',
        '<div class="well well-sm query-form">',
            '<form class="form-horizontal">',
                '<div class="form-group row">',
                    '<div class="col-sm-2 m-l" id="tableName">',
                        '<select class="form-control"></select>',
                    '</div>',
                    '<div class="col-sm-2 m-l">',
                        '<label class="control-label"><input type="checkbox" name="isRoom" />&nbsp;包间</label>',
                    '</div>',
                    '<div class="col-md-2 pull-right">',
                        '<button class="btn btn-warning" name="addTable">新增桌台</button>',
                    '</div>',
                '</div>',
            '</form>',
        '</div>',
        '<div id="foodSearchResult">相关结果 (<span></span>)</div>',
    ].join('');
    TplLib.register('tpl_table_query', tpl_table_query);

    var tpl_edit_table_modal = [
        '<form class="form-horizontal form-table">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">所属区域*</label>',
                '<div class="col-sm-5" name="tableArea">',
                '</div>',
            '</div>',
			'<div class="form-group">',
				'<label class="col-sm-offset-1 col-sm-3 control-label">桌台编号 </label>',
				'<div class="col-sm-5">',
					'<input type="text" class="form-control" name="tableCode" value="{{tableCode}}"/>',
				'</div>',
			'</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">桌台名称*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="tableName" value="{{tableName}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">席位数*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="person" value="{{person}}"/>',
                '</div>',
            '</div>',
            '{{#each radios}}',
                '<div class="form-group">',
                    '{{#with this}}',
                        '{{> customRadio}}',
                    '{{/with}}',
                '</div>',
            '{{/each}}',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label" for="description">标签备注 </label>',
                '<div class="col-sm-5">',
                    '<input placeholder="多个标签用英文“,”隔开" class="form-control" name="tableTagStr" value="{{tableTagStr}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">留台单打印机</label>',
                '<div class="col-sm-5" name="printer">',
                '</div>',
            '</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_table', tpl_edit_table_modal);

    var tpl_edit_table_area = [
        '<form class="form-horizontal form-area">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">区域名称*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="areaName" value="{{areaName}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">区域描述</label>',
                '<div class="col-sm-5">',
                    '<textarea type="text" class="form-control" name="areaNote">{{areaNote}}</textarea>',
                '</div>',
            '</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_table_area', tpl_edit_table_area);

    var tpl_checkbox = [
        '<form class="form-horizontal">',
			'<h5 class="page-header">区域: {{areaName}}</h5>',
            '<div class="form-group">',
                '<label class="control-label"><input type="radio" {{allChecked}} name="isCustom" />&nbsp;全部菜品</label>',
				'<br>',
                '<label class="control-label m-t"><input type="radio" {{customChecked}} name="isCustom" />&nbsp;自定义</label>',
            '</div>',
            '<div class="form-group">',
                '{{#each checkboxes}}',
                    '<label class="col-sm-3"><input type="checkbox" {{checked}} {{disabled}} name="category" data-key="{{categoryCode}}" />&nbsp;{{text}}</label>',
                '{{/each}}',
            '</div>',
        '</form>'
    ].join('');
    Hualala.TplLib.register('tpl_checkbox', tpl_checkbox);

    var tpl_radio = [
        '<label class="{{labelOffset}} col-sm-3 control-label">{{label}} </label>',
        '<div class="col-sm-5">',
            '{{#each inputs}}',
                '<label class="control-label m-r"><input type="radio" {{checked}} name="{{../name}}" value="{{value}}"/> {{text}}</label>',
            '{{/each}}',
        '</div>',
    ].join('');
    Hualala.TplLib.register('tpl_radio', tpl_radio);

    var tpl_table_info = [
		'<div class="qr-img col-md-4 m-t">',
			'<label class="control-label">自助二维码</label>',
			'<img class="m-t" src="{{qrImagePath}}">',
		'</div>',
        '<table>',
            '{{#each basicInfo}}',
                '<tr>',
                    '<td>{{label}}:</td>',
                    '<td>{{value}}</td>',
                '</tr>',
            '{{/each}}',
        '</table>'
    ].join('');
    Hualala.TplLib.register('tpl_table_info', tpl_table_info);

    var tpl_promotion_add = [
	'<div class="well well-sm t-r promotion_operate">',
		'{{#if noRef}}',
		'<p class="controls">',
			'<span class="controls">可<a href="javascript:;" class="operate" data-type="refPromotionRules">套用</a>其它店铺促销规则</span>',
			'<button class=" operate btn btn-warning" data-type="addPromotion">添加店铺促销</button>',
		'</p>',
		'{{else}}',
		'<p class="controls">',
			'<span class="controls">本店促销规则套用 {{refShopName}} 不可编辑,您可以<a href="javascript:;" class="operate" data-type="refPromotionRules">修改套用</a>或<a href="javascript:;" class="operate" data-type="cancelrefPromotionRules">取消套用</a></span>',
		'</p>',
		'{{/if}}',
		
	'</div>'
    ].join('');
    Hualala.TplLib.register('tpl_promotion_add', tpl_promotion_add);
    var tpl_promotion_refRules = [
    '<div class="alert alert-warning  refPromotionRules">{{refPromotionRulesDesc}}</div>'
    ].join('');
    Hualala.TplLib.register('tpl_promotion_refRules', tpl_promotion_refRules);

    var tpl_printer_add = [
	'<div class="well well-sm t-r promotion_add">',
		'<p class="controls">',
			'<button class=" operate btn btn-warning" data-type="addPrinter">添加打印机</button>',
		'</p>',
	'</div>'
    ].join('');
    Hualala.TplLib.register('tpl_printer_add', tpl_printer_add);

    var tpl_edit_printer = [
        '<form class="form-horizontal printer-form">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机名称*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="printerName" value="{{printerData.printerName}}"/>',
                '</div>',
            '</div>',
            /*'<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机状态*</label>',
                '<div class="col-sm-5">',
                    '<select name="currPrinterStatus"  class="form-control">',
                    	'<option value="">--请tpl_checkbox--</option>',
                        '{{#each PrinterStatusData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',*/
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机端口类型*</label>',
                '<div class="col-sm-5">',
                    '<select name="printerPortType"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each printerPortData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机端口*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="printerPort" value="{{printerData.printerPort}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机品牌*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="printerBrand" value="{{printerData.printerBrand}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机型号</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="printerModel" value="{{printerData.printerModel}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">纸张宽度</label>',
                '<div class="col-sm-5">',
                    '<select name="printerPaperSize"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each PaperSizesData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">打印机说明</label>',
                '<div class="col-sm-5">',
                    '<textarea type="text" class="form-control" name="printerRemark">{{printerData.printerRemark}}</textarea>',
                '</div>',
            '</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_printer', tpl_edit_printer);


    var tpl_printerArea_queryBox =[
         '<div class="panel panel-default clearfix">',
            '<div class="col-md-2 pull-right">',
                '<a class="btn btn-warning" href="{{areaLink}}">打印机设置</a>',
            '</div>',
        '</div>',
        '<div class="well well-sm query-form">',
            '<form class="form-horizontal">',
            	'<div class="row">',
		           	'<div class="col-md-3 ">',
		           		'<div class="form-group">',
			                '<label class="col-xs-2 col-sm-2 col-md-4 control-label">区域名称:</label>',
			                '<div class="col-xs-8 col-sm-8 col-md-8">',
			                    '<select class="form-control" name="areaKey">',
			                    '</select>',
			                '</div>',
		                '</div>',
		            '</div>',
		           	'<div class="col-md-3 ">',
		           		'<div class="form-group">',
			                '<label class="col-xs-2 col-sm-2 col-md-4 control-label">部门名称:</label>',
			                '<div class="col-xs-8 col-sm-8 col-md-8">',
			                    '<select class="form-control " name="departmentKey">',
			                    '</select>',
			                '</div>',
		                '</div>',
		            '</div>',
		           	'<div class="col-md-3 ">',
		           		'<div class="form-group">',
			                '<label class="col-xs-2 col-sm-2 col-md-4 control-label">打印机名称:</label>',
			                '<div class="col-xs-8 col-sm-8 col-md-8">',
			                  	'<select class="form-control " name="printerKey">',
			                    '</select>',
			                '</div>',
		                '</div>',
		            '</div>',
	                '<div class="col-md-3 ">',
		           		'<div class="form-group">',
		                    '<div class="col-xs-8 col-sm-8 col-md-8 pull-right">',
		                        '<button type="button" class="btn btn  btn-warning operate" data-type="search" name="button">查询</button>',
		                    '</div>',
		                '</div>',
		            '</div>',
	            '</div>',
            '</form>',
        '</div>',
       '<div class="row printer-areaSet">',
       	    '<div class="col-md-2 pull-right">',
	            '<button class="btn btn-warning operate" data-type="areaSet">设置传菜单打印机</button>',
	    	'</div>',
       	   	'<div class="col-md-2 pull-right">',
	            '<button class="btn btn-warning operate" data-type="departSet">设置制作单打印机</button>',
	    	'</div>',
	    '</div>',
        '<div class="shop-list">',
        '</div>'].join('');
    Hualala.TplLib.register('tpl_printerArea_queryBox', tpl_printerArea_queryBox);

    var tpl_edit_printerAreaSet = [
        '<form class="form-horizontal printer-form">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">制作单打印机*</label>',
                '<div class="col-sm-5">',
                    '<select name="printerKey"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each areaprinters}}',
                        '<option value="{{this.printerKey}}" {{selected}}>{{this.printerName}}</option>',
                        '{{/each}}',
                    '</select>',
                    '<span class="help-block">提醒：如打印机没有可选项，请先添加打印机</span>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">制作单打印方式*</label>',
                '<div class="col-sm-5">',
                    '<select name="printWay"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each PrintTypeData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.title}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">制作单打印份数*</label>',
                '<div class="col-sm-5">',
                    //'<input type="text" class="form-control" name="printCopies" value="{{printCopies}}"/>',
                	'<select name="printCopies"  class="form-control">',
                        '{{#each AreaprintCopies}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',
            '</div>',
	        '<div class="form-group">',
	            '<label class="col-sm-offset-1 col-sm-3 control-label">是否打印传菜单上*</label>',
	            '<div class="col-sm-5">',
	                '<input type="checkbox" class="status" name="isPrintToDispatchBill" data-status="{{isPrintToDispatchBill}}">',
	        	'</div>',
        	'</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_printerAreaSet', tpl_edit_printerAreaSet);
    var tpl_edit_printerArea = [
        '<form class="form-horizontal printer-form">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">传菜单打印机*</label>',
                '<div class="col-sm-5">',
                    '<select name="dispatchBillPrinterKey"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each areaprinters}}',
                        '<option value="{{this.printerKey}}" {{selected}}>{{this.printerName}}</option>',
                        '{{/each}}',
                    '</select>',
                    '<span class="help-block">提醒：如打印机没有可选项，请先添加打印机</span>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">传菜单打印份数*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="dispatchBillPrintCopies" value="{{dispatchBillPrintCopies}}"/>',
                '</div>',
            '</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_printerArea', tpl_edit_printerArea);

    var tpl_edit_discount = [
        '<form class="form-horizontal discount-form">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">折扣名称*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="discountWayName" value="{{discountData.discountWayName}}"/>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">折扣范围*</label>',
                '<div class="col-sm-5">',
                    '<select name="discountRange"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each discountRangeData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">折扣率*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="discountRate" value="{{discountData.discountRate}}"/>',
                    '<span class="help-block">提醒：折扣率为0-1的数字且小数点后最多为两位，如0.88代表8.8折,1.00代表不打折</span>',
                '</div>',
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">是否享受会员价*</label>',
                '<div class="col-sm-5">',
                    '<select name="isVipPrice"  class="form-control">',
                    	'<option value="">--请选择--</option>',
                        '{{#each isVipPriceData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">是否启用*</label>',
                '<div class="col-sm-5">',
                    '<select name="isActive"  class="form-control">',
                        '{{#each isActiveData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">折扣描述</label>',
                '<div class="col-sm-5">',
                    '<textarea type="text" class="form-control" name="discountWayRemark">{{discountData.discountWayRemark}}</textarea>',
                '</div>',
            '</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_discount', tpl_edit_discount);

    var tpl_Time_add = [
	'<div class="alert alert-warning t-c Time_operate ">',
		'{{#if noRef}}',
		'<p class="controls">',
			'<span class="controls">可&nbsp;&nbsp;<a href="javascript:;" class="operate" data-type="refTime">套用</a>&nbsp;&nbsp;其它店铺营业时段</span>',
		'</p>',
		'{{else}}',
		'<p class="controls">',
			'<span class="controls">本店营业时段套用 {{refTimeShopName}} 不可编辑,您可以<a href="javascript:;" class="operate" data-type="refTime">修改套用</a>或<a href="javascript:;" class="operate" data-type="cancleRefShopTime">取消套用</a></span>',
		'</p>',
		'{{/if}}',
		
	'</div>'
    ].join('');
    Hualala.TplLib.register('tpl_Time_add', tpl_Time_add);

    var tpl_edit_shoptime = [
        '<form class="form-horizontal discount-form">',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">餐段名称*</label>',
                '<div class="col-sm-5">',
                    '<input type="text" class="form-control" name="timeName" value="{{timeData.timeName}}"/>',
                '</div>',
            '</div>',
			'<div class="form-group">',
				'<label class="col-sm-offset-1 col-sm-3 control-label">开始时间*</label>',
				'<div class="col-xs-5">',
					'<div class="input-group">',
						'<input type="text" name="startTime" class="form-control" value="{{timeData.startTime}}" data-type="timepicker">',
				        '<span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>',
				    '</div>',
				'</div>',
			'</div>',
			'<div class="form-group">',
				'<label class="col-sm-offset-1 col-sm-3 control-label">结束时间*</label>',
				'<div class="col-xs-5">',
					'<div class="input-group">',
						'<input type="text" name="endTime" class="form-control" value="{{timeData.endTime}}" data-type="timepicker">',
				        '<span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>',
				    '</div>',
				'</div>',
			'</div>',
            '<div class="form-group">',
                '<label class="col-sm-offset-1 col-sm-3 control-label">是否启用*</label>',
                '<div class="col-sm-5">',
                    '<select name="isActive"  class="form-control">',
                        '{{#each isActiveData}}',
                        '<option value="{{this.value}}" {{selected}}>{{this.label}}</option>',
                        '{{/each}}',
                    '</select>',
                '</div>',                
            '</div>',
        '</form>'].join('');
    Hualala.TplLib.register('tpl_edit_shoptime', tpl_edit_shoptime);


    var tpl_promotion_base_form = [
		'{{#if isDivForm}}',
		'<div class="form-horizontal {{formClz}}" role="form">',
		'{{else}}',
		'<form class="form-horizontal {{formClz}}" role="form">',
		'{{/if}}',
			'{{#each items}}',
				'{{#checkFormElementType type type="radioDiv"}}',
				'</p>请选择促销方式</p>',
				'<div class="form-group">',
					//'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
					'{{#each options}}',
					'<div class="col-sm-offset-2 col-sm-8 alert alert-warning promotin-stageType">',
						'<label class="">',
							'<input type="radio" name="{{name}}" {{disabled}} id="{{id}}" value="{{value}}" {{checked}} />',
							'{{label}}',
						'</label>',
						'<label class="help-block">{{help}}</label>',
					'</div>',
					'{{/each}}',
				'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="static"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<p class="form-control-static">{{value}}</p>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="textarea"}}',
					'<div class="form-group {{hidden}}">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
								'<textarea id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}" data-type="{{type}}" {{mode}}>{{{value}}}</textarea>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="text"}}',
					'<div class="form-group  {{hidden}}">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'{{#isInputGroup prefix surfix}}',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}" data-type="{{type}}" {{disabled}} {{readonly}} {{mode}} />',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'{{else}}',
								'<input type="text" id="{{id}}" name="{{name}}" class="form-control {{hidden}}" placeholder="{{placeholder}}" value="{{value}}" data-type="{{type}}" {{disabled}} {{readonly}} {{mode}}/>',
							'{{/isInputGroup}}',
							'{{#if help}}',
								'<span class="help-block">{{{help}}}</span>',
							'{{/if}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="radiogrp"}}',
					'<div class="form-group {{hidden}}">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#each options}}',
								'<label class="radio-inline {{clz}}">',
									'<input type="radio" name="{{name}}" {{disabled}} id="{{id}}" value="{{value}}" {{checked}} />',
									'{{label}}',
								'</label>',
							'{{/each}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="checkboxgrp"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'{{#each options}}',
								'<label class="checkbox-inline {{clz}}">',
									'<input type="checkbox" name="{{name}}" {{disabled}} id="{{id}}" value="{{value}}" {{checked}} />',
									'{{label}}',
								'</label>',
							'{{/each}}',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="selectShops"}}',
					'<div class="form-group">',
						'<label for="" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<div class="combo-shop" name="{{name}}"></div>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="hidden"}}',
					'<input type="hidden" id="{{id}}" name="{{name}}" value="{{value}}" />',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="inputCountCycleDays"}}',
					'<div class="form-group">',
						'<label for="" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<div class="cycle-box">',
								'{{#with countCycleDays}}',
									'<span class="cycle-label">',
										'同一用户',
									'</span>',
									'<select id="{{id}}" name="{{name}}" class="form-control">',
										'{{#each options}}',
											'<option value="{{value}}" {{selected}}>{{label}}</option>',
										'{{/each}}',
									'</select>',
								'{{/with}}',
								'{{#with partInTimes}}',
									'<span class="partin-label">',
										'总共可参与',
									'</span>',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" value="{{value}}" />',
									'<span class="partin-label">',
										'次',
									'</span>',
								'{{/with}}',
							'</div>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="section"}}',
					'<div class="form-group section">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'{{#with min}}',
							'<div class="min-input {{clz}}">',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}" {{readonly}}  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'</div>',
						'{{/with}}',
						'{{#with max}}',
							'<div class="max-input {{clz}}">',
								'<span class="to-label">到</span>',
								'<div class="input-group">',
									'{{#if prefix}}',
										'<span class="input-group-addon">',
											'{{{prefix}}}',
										'</span>',
									'{{/if}}',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" placeholder="{{placeholder}}" value="{{value}}" {{readonly}}  data-type="{{type}}">',
									'{{#if surfix}}',
										'<span class="input-group-addon">',
											'{{{surfix}}}',
										'</span>',
									'{{/if}}',
								'</div>',
							'</div>',
						'{{/with}}',
					'</div>',
				'{{/checkFormElementType}}',
				
				'{{#checkFormElementType type type="pickgift"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<div class="input-group">',
								'<input type="text" readonly id="{{id}}" name="{{name}}" value="{{value}}" class="form-control" />',
								'<span class="input-group-btn">',
									'<button class="btn btn-default" name="pickgift" type="button">选择</button>',
								'</span>',
							'</div>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="switcher"}}',
					'<div class="form-group">',
						'<label for="{{id}}" class="{{labelClz}}">{{label}}</label>',
						'<div class="{{clz}}">',
							'<input type="checkbox" id="{{id}}" name="{{name}}" value="{{defaultVal}}" data-type="{{type}}" data-onLabel="{{onLabel}}" data-offLabel="{{offLabel}}" {{checked}} />',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
				'{{#checkFormElementType type type="inputCountCycleDays"}}',
					'<div class="form-group">',
						'<label for="" class="{{labelClz}}">{{{label}}}</label>',
						'<div class="{{clz}}">',
							'<div class="cycle-box">',
								'{{#with partInTimes}}',
									'<span class="partin-label">',
										'每满',
									'</span>',
									'<input type="text" id="{{id}}" name="{{name}}" class="form-control" value="{{value}}" />',
									'<span class="partin-label">',
										'元',
									'</span>',
								'{{/with}}',
							'</div>',
						'</div>',
					'</div>',
				'{{/checkFormElementType}}',
			'{{/each}}',
		'{{#if isDivForm}}',
		'</div>',
		'{{else}}',
		'</form>',
		'{{/if}}'
	].join('');
	TplLib.register('tpl_promotion_base_form', tpl_promotion_base_form);

})(jQuery, window);